"""
Django settings for qualidade_project project.

Generated by 'django-admin startproject' using Django 4.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

from pathlib import Path
import environ
import os
import certifi, os
from django.contrib.messages import constants as messages

# from .mongo_api import conect_mongo_db

env = environ.Env()
environ.Env.read_env()

os.environ["SSL_CERT_FILE"] = certifi.where()

PROJECT_ROOT = os.path.abspath(os.path.dirname(__file__))


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("SECRET_KEY")
FARMBOX_ID = env("FARM_API")
MONGO_PASS_DEFENSIVOS = env("MONGO_PASS_DEFENSIVOS")
PROTHEUS_TOKEN = env("PROTHEUS_TOKEN")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG_ENV = env("DEBUG")
if DEBUG_ENV == "1":
    DEBUG = True
if DEBUG_ENV == "0":
    DEBUG = False
print('DEBUG', DEBUG)

ALLOWED_HOSTS = ["*"]

KML_DEBUG_SAVE = os.getenv("KML_DEBUG_SAVE", "0")



# Application definition

CORS_ALLOW_ALL_ORIGINS = True


INSTALLED_APPS = [
    # General use templates & template tags (should appear first)
    "adminlte3",
    # Optional: Django admin theme (must be before django.contrib.admin)
    "adminlte3_theme",
    # "admin_material.apps.AdminMaterialDashboardConfig",  # <-- NEW
    "admin_confirm",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django_crontab",
    "django_apscheduler",
    "django_dbconn_retry",
    # "diamante.apps.DiamanteConfig",
    "csvexport",
    "debug_toolbar",
    "django_json_widget",
    "rest_framework",
    "rest_framework.authtoken",
    "corsheaders",
    "usuario",
    "diamante",
    "admin_extra_buttons",
    "crispy_forms",
    "crispy_bootstrap4",
    "storages",
    "aviacao",
    "anymail",
    "kmltools",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    'django.middleware.gzip.GZipMiddleware',
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "debug_toolbar.middleware.DebugToolbarMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    # 'diamante.middleware.AdminTokenAuthenticationMiddleware'
]


# SESSION_ENGINE = "django.contrib.sessions.backends.cache"
# SESSION_CACHE_ALIAS = "default"  # Use the default cache, or specify another cache alias

APPEND_SLASH = False
PREPEND_WWW = False

WHITENOISE_USE_FINDERS = True  # Allow WhiteNoise to serve static files
WHITENOISE_MAX_AGE = 31536000  # 1 year in seconds for versioned files


CSRF_TRUSTED_ORIGINS = [
    "https://diamante-quality.up.railway.app",
    "http://localhost:3000",
    "https://diamanteubs.netlify.app",
]

ROOT_URLCONF = "qualidade_project.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, "templates")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "qualidade_project.wsgi.application"

# EMAIL CONFIG

# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_BACKEND = "anymail.backends.sendinblue.EmailBackend"

# Chave da API MailerSend
# ANYMAIL = {
#     "SENDINBLUE_API_KEY": env("SENDINBLUE_API_KEY"),
# }

# EMAIL_HOST = 'smtp.gmail.com'
# EMAIL_HOST = 'smtp-relay.sendinblue.com'
# EMAIL_PORT = 465
# EMAIL_USE_TLS = False
# EMAIL_USE_SSL = True
# EMAIL_HOST_PASSWORD = env("EMAIL_HOST_PASSWORD_CONFIG")

EMAIL_HOST_USER = 'patamarcelo@gmail.com'


# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

use_db = "default"
# use_db_dev = "dev"

DATABASES = {
    # "dev": {
    #     'ENGINE': 'django.db.backends.postgresql',
    #     "NAME": env("DB_EL_NAME_NEON", default="default_db_name"),
    #     "USER": env("DB_EL_USER_NEON", default="default_user"),
    #     "PASSWORD": env("DB_EL_PASSWORD_NEON", default="default_password"),
    #     "HOST": env("DB_EL_HOST_NEON", default="localhost"),
    #     "PORT": env("DB_EL_PORT_NEON", default="5432"),
    #     'CONN_MAX_AGE': 600,
    #     'OPTIONS': {
    #         'sslmode': 'require',
    #         'connect_timeout': 10,
    #     },
    #     "CONN_HEALTH_CHECKS": True,
    #     'ATOMIC_REQUESTS': True,
    # },
    "default": {
        'ENGINE': 'django.db.backends.postgresql',
        "NAME": env("DB_EL_NAME"),
        "USER": env("DB_EL_USER"),
        "PASSWORD": env("DB_EL_PASSWORD"),
        "HOST": env("DB_EL_HOST"),
        "PORT": env("DB_EL_PORT"),
        # 'CONN_MAX_AGE': 10,  # Keep connections alive for 5 minutes
        "CONN_HEALTH_CHECKS": True,  # check connection before using
        'ATOMIC_REQUESTS': True,
        'POOL_OPTIONS': {
            'POOL_SIZE': 10,        # Increase from 5
            'MAX_OVERFLOW': 20,     # Increase from 10
            'RECYCLE': 300,
            'PRE_PING': True,
        }
    },
    # "dev": {
    #     'ENGINE': 'dj_db_conn_pool.backends.postgresql',
    #     "NAME": env("DB_EL_NAME_LOCAL"),
    #     "USER": env("DB_EL_USER_LOCAL"),
    #     "PASSWORD": env("DB_EL_PASSWORD_LOCAL"),
    #     "HOST": env("DB_EL_HOST_LOCAL"),
    #     "PORT": env("DB_EL_PORT_LOCAL"),
    #     'POOL_OPTIONS': {
    #         'POOL_SIZE': 20,            # Number of connections in the pool
    #         'MAX_OVERFLOW': 10,         # Extra connections beyond the pool size
    #         'RECYCLE': 1800,            # Recycle connections after a certain time to avoid stale connections
    #         'PRE_PING': True,           # Check connections before using them to avoid using a broken connection
    #     }
    # },
}

DATABASES["default"] = DATABASES[use_db]


# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/


LOGOUT_REDIRECT_URL = "index"
LOGIN_URL = "index"


THOUSAND_SEPARATOR = (".",)

USE_THOUSAND_SEPARATOR = True

LANGUAGE_CODE = "pt-br"

TIME_ZONE = "America/Sao_Paulo"

USE_I18N = True

USE_L10N = True

USE_TZ = True


AUTH_USER_MODEL = "usuario.CustomUsuario"


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

# STATIC_URL = "static/"

STATIC_URL = "/static/"
# STATIC_ROOT = os.path.join(BASE_DIR, "static")

# DEFAULT_FILE_STORAGE = "storages.backends.dropbox.DropBoxStorage"
STORAGES = {
    "default": {
        "BACKEND": "storages.backends.dropbox.DropboxStorage",
        "OPTIONS": {},
    },
    "staticfiles": {"BACKEND": "whitenoise.storage.CompressedStaticFilesStorage"},
}

DROPBOX_ROOT_PATH = "/"


DROPBOX_OAUTH2_REFRESH_TOKEN = env("DROPBOX_OAUTH2_REFRESH_TOKEN", default="")
DROPBOX_APP_SECRET = env("DROPBOX_APP_SECRET", default="")
DROPBOX_APP_KEY = env("DROPBOX_APP_KEY", default="")


MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media/")
# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


REST_AUTH_SERIALIZERS = {
    "USER_DETAILS_SERIALIZER": "path.to.custom.UserSerializer",
}

STATICFILES_DIRS = [os.path.join(BASE_DIR, "static")]
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")
# STATICFILES_STORAGE = "whitenoise.storage.CompressedStaticFilesStorage"


INTERNAL_IPS = [
    "127.0.0.1",
]

CRISPY_TEMPLATE_PACK = "bootstrap4"

CRONJOBS = [
    ('* * * * *', 'diamante.cron.get_hour_test')
]

ENABLE_CRON_REGISTER = True


# LOGGING = {
#     'version': 1,
#     'disable_existing_loggers': False,
#     'handlers': {
#         'console': {
#             'class': 'logging.StreamHandler',
#         },
#     },
#     'loggers': {
#         'django.db.backends': {
#             'level': 'DEBUG',
#             'handlers': ['console'],
#         },
#     },
# }





MESSAGE_TAGS = {
    messages.DEBUG: 'debug',
    messages.INFO: 'info',
    messages.SUCCESS: 'success',
    messages.WARNING: 'warning',  # garante que WARNING = alert-warning
    messages.ERROR: 'danger',      # bootstrap usa "danger" em vez de "error"
}


# settings.py
KML_NETLINK_ALLOWED_HOST_SUFFIXES = ("google.com", "googleusercontent.com", "maps.google.com", "www.google.com")
KML_NETLINK_MAX_BYTES = 8 * 1024 * 1024
KML_NETLINK_CONNECT_TIMEOUT = 3
KML_NETLINK_READ_TIMEOUT = 6
KML_NETLINK_MAX_REDIRECTS = 3
KML_NETLINK_CACHE_TTL = 60 * 60
