# Generated by Django 5.0 on 2024-03-07 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TecnicoAgricola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criados', models.DateTimeField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
                ('crea_number', models.CharField(max_length=100, unique=True, verbose_name='Numero do CREA')),
            ],
            options={
                'verbose_name': 'Técnico Agrícola',
                'verbose_name_plural': 'Técnicos Agrícola',
            },
        ),
    ]
