# Generated by Django 5.0 on 2024-03-12 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aviacao', '0001_initial'),
        ('diamante', '0089_plantio_area_aferida'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aeronave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criados', models.DateTimeField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('prefixo', models.CharField(max_length=100, unique=True, verbose_name='Prefixo Aero')),
            ],
            options={
                'verbose_name': 'Aeronave',
                'verbose_name_plural': 'Aeronaves',
            },
        ),
        migrations.CreateModel(
            name='EngenheiroAgronomo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criados', models.DateTimeField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
                ('crea_number', models.CharField(max_length=100, unique=True, verbose_name='Numero do CREA')),
            ],
            options={
                'verbose_name': 'Técnico Agrícola',
                'verbose_name_plural': 'Técnicos Agrícola',
            },
        ),
        migrations.CreateModel(
            name='Piloto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criados', models.DateTimeField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('nome', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome')),
                ('anac', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nº ANAC')),
            ],
            options={
                'verbose_name': 'Piloto',
                'verbose_name_plural': 'Pilotos',
            },
        ),
        migrations.CreateModel(
            name='Pista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criados', models.DateTimeField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('nome', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome da Pista')),
                ('coordenadas', models.JSONField(blank=True, null=True)),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='diamante.projeto')),
            ],
            options={
                'verbose_name': 'Pista',
                'verbose_name_plural': 'Pistas',
            },
        ),
    ]
