# Generated by Django 5.0 on 2024-03-12 15:39

import aviacao.models
import django.db.models.deletion
import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aviacao', '0002_aeronave_engenheiroagronomo_piloto_pista'),
        ('diamante', '0089_plantio_area_aferida'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ajudante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criados', models.DateTimeField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('nome', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome Ajudante')),
            ],
            options={
                'verbose_name': 'Ajudante',
                'verbose_name_plural': 'Ajudantes',
            },
        ),
        migrations.CreateModel(
            name='Gerente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criados', models.DateTimeField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('nome', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome do Gerente')),
                ('projeto', models.ManyToManyField(to='diamante.projeto')),
            ],
            options={
                'verbose_name': 'Gerente',
                'verbose_name_plural': 'Gerentes',
            },
        ),
        migrations.CreateModel(
            name='OrdemDeServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criados', models.DateTimeField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('numero', models.PositiveIntegerField(unique=True)),
                ('data', models.DateField(help_text='dd/mm/aaaa', verbose_name='Data')),
                ('area', models.DecimalField(blank=True, decimal_places=2, help_text='Informar Área da Aplicação', max_digits=10, null=True, verbose_name='Area')),
                ('combustivel', models.DecimalField(blank=True, decimal_places=2, help_text='Informar Quantidade de Combustível', max_digits=10, null=True, verbose_name='Combustível / Litros')),
                ('os_file', models.ImageField(upload_to=aviacao.models.get_img_upload_path, verbose_name='Imagem')),
                ('data_inicial', models.DateField(help_text='dd/mm/aaaa', verbose_name='Data Inicial Aplicação')),
                ('data_final', models.DateField(help_text='dd/mm/aaaa', verbose_name='Data Final Aplicação')),
                ('horimetro_inicial', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Horímetro Inicial')),
                ('horimetro_final', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Horímetro Final')),
                ('tempo_aplicacao', models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(models.F('horimetro_final'), '-', models.F('horimetro_inicial')), output_field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Tempo Aplicacao'))),
                ('oleo_lubrificante', models.DecimalField(blank=True, decimal_places=2, help_text='Quantidade de óleo Utilizado', max_digits=10, null=True, verbose_name='Óelo Lubrificante')),
                ('tipo_servico', models.CharField(choices=[('acaricida', 'Acaricida'), ('adjuvante', 'Adjuvante'), ('biologico', 'Biológico'), ('cobertura', 'Cobertura'), ('fertilizante', 'Fertilizante'), ('fungicida', 'Fungicida'), ('herbicida', 'Herbicida'), ('inseticida', 'Inseticida'), ('lubrificante', 'Lubrificante'), ('nutricao', 'Nutrição'), ('oleo_mineral_vegetal', 'Óleo Mineral/Vegetal'), ('protetor', 'Protetor'), ('regulador', 'Regulador'), ('semente', 'Semente')], max_length=80, verbose_name='Tipo Serviço')),
                ('uso_gps', models.BooleanField(default=False, help_text='Informar se foi utilizado o GPS do Avião', verbose_name='Utilizado o GPS ? ')),
                ('volume', models.DecimalField(blank=True, decimal_places=2, help_text='Informar Volume Utilizado por hectare', max_digits=10, null=True, verbose_name='Volume Litros ou Kg/ha')),
                ('aeronave', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aviacao.aeronave')),
                ('ajudante', models.ManyToManyField(to='aviacao.ajudante')),
                ('cultura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='diamante.cultura')),
                ('encarregado_autoriza', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aviacao.gerente')),
                ('engenheiro_agronomo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='aviacao.engenheiroagronomo')),
                ('piloto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aviacao.piloto')),
                ('pista', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aviacao.pista')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='diamante.projeto')),
                ('tecnico_agricola_executor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='aviacao.tecnicoagricola')),
            ],
            options={
                'verbose_name': 'Ordem de Serviço',
                'verbose_name_plural': 'Ordens de Serviço',
            },
        ),
    ]
