# Generated by Django 5.0 on 2024-03-12 16:12

import aviacao.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aviacao', '0003_ajudante_gerente_ordemdeservico'),
        ('diamante', '0089_plantio_area_aferida'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParametrosAplicacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criados', models.DateTimeField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='ordemdeservico',
            name='os_file',
            field=models.ImageField(upload_to=aviacao.models.get_img_upload_path, verbose_name='Ordem de Serviço'),
        ),
        migrations.CreateModel(
            name='CondicoesMeteorologicas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criados', models.DateTimeField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('temperatura_inicial', models.PositiveIntegerField()),
                ('temperatura_final', models.PositiveIntegerField()),
                ('umidade_relativa_incial', models.PositiveIntegerField()),
                ('umidade_relativa_final', models.PositiveIntegerField()),
                ('velocidade_vento_inicial', models.PositiveIntegerField()),
                ('velocidade_vento_final', models.PositiveIntegerField()),
                ('os', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aviacao.ordemdeservico')),
            ],
            options={
                'verbose_name': 'Condições Metereológicas',
                'verbose_name_plural': 'Condições Metereológicas',
            },
        ),
        migrations.CreateModel(
            name='TempoAplicacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criados', models.DateTimeField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('inicio_aplicacao', models.DateTimeField(verbose_name='Início da Aplicação')),
                ('final_aplicacao', models.DateTimeField(verbose_name='Final da Aplicação')),
                ('os', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aviacao.ordemdeservico')),
            ],
            options={
                'verbose_name': 'Tempo Aplicação',
                'verbose_name_plural': 'Tempo Aplicação',
            },
        ),
        migrations.CreateModel(
            name='AplicacaoAviao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criados', models.DateTimeField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('dose', models.DecimalField(decimal_places=3, help_text='Dose aplicada de Kg ou Lt por ha.', max_digits=8, verbose_name='Dose KG/LT por ha')),
                ('obs', models.TextField(blank=True, max_length=500, verbose_name='Observação')),
                ('defensivo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='diamante.defensivo')),
                ('os', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='os_related_aplicacao', to='aviacao.ordemdeservico')),
            ],
            options={
                'verbose_name': 'Aplicação Avião',
                'verbose_name_plural': 'Aplicações Avião',
                'ordering': ['os', 'defensivo'],
                'unique_together': {('os', 'defensivo', 'ativo', 'dose')},
            },
        ),
    ]
