# Generated by Django 5.0 on 2024-03-12 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aviacao', '0004_parametrosaplicacao_alter_ordemdeservico_os_file_and_more'),
        ('diamante', '0089_plantio_area_aferida'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemdeservico',
            name='valor_combustivel',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor do Combustível por Litro'),
        ),
        migrations.CreateModel(
            name='TabelaPilotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criados', models.DateTimeField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('vazao', models.PositiveIntegerField()),
                ('preco', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Preço por Hectare')),
                ('ciclo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='diamante.ciclo')),
                ('safra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='diamante.safra')),
            ],
            options={
                'verbose_name': 'Tabela Preço Piloto',
                'verbose_name_plural': 'Tabela Preço Pilotos',
            },
        ),
    ]
