# Generated by Django 5.0 on 2024-03-20 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aviacao', '0005_ordemdeservico_valor_combustivel_tabelapilotos'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ParametrosAplicacao',
        ),
        migrations.AlterModelOptions(
            name='tabelapilotos',
            options={'verbose_name': 'Preço do Piloto', 'verbose_name_plural': 'Preços dos Pilotos'},
        ),
    ]
