# Generated by Django 5.0 on 2024-03-20 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aviacao', '0006_delete_parametrosaplicacao_and_more'),
        ('diamante', '0089_plantio_area_aferida'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParametrosAplicacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criados', models.DateTimeField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('temperatura_max', models.PositiveIntegerField()),
                ('umidade_relativa_min', models.PositiveIntegerField()),
                ('umidade_relativa_ax', models.PositiveIntegerField()),
                ('altura_do_voo', models.PositiveIntegerField()),
                ('largura_da_faixa', models.PositiveIntegerField()),
                ('receituario_agronomo_n', models.PositiveIntegerField()),
                ('data_emissao', models.DateField(help_text='dd/mm/aaaa', verbose_name='Emitido em')),
                ('os', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aviacao.ordemdeservico')),
                ('parcelas', models.ManyToManyField(to='diamante.plantio')),
            ],
            options={
                'verbose_name': 'Parâmetros Básicos de Apicação',
                'verbose_name_plural': 'Parâmetros Básicos de Apicações',
            },
        ),
    ]
