# Generated by Django 5.0 on 2024-03-20 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aviacao', '0007_parametrosaplicacao'),
        ('diamante', '0089_plantio_area_aferida'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aplicacaoaviao',
            options={'ordering': ['os', 'defensivo'], 'verbose_name': 'Aplicação - Produto Aplicado', 'verbose_name_plural': 'Aplicações - Produtos Aplicados'},
        ),
        migrations.AddField(
            model_name='parametrosaplicacao',
            name='equipamento',
            field=models.CharField(choices=[('bico', 'Bico'), ('atomizador', 'Atomizador'), ('swathmaster', 'Swathmaster')], default=1, max_length=100, verbose_name='Equipamento utilizado'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tabelapilotos',
            name='tipo',
            field=models.CharField(choices=[('turbo', 'Turbo'), ('ipanema', 'Ipanema')], default=1, max_length=100, verbose_name='Tipo Avião'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='tabelapilotos',
            unique_together={('tipo', 'safra', 'ciclo', 'vazao', 'preco')},
        ),
    ]
