# Generated by Django 5.0 on 2024-03-20 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aviacao', '0008_alter_aplicacaoaviao_options_and_more'),
        ('diamante', '0089_plantio_area_aferida'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parametrosaplicacao',
            name='parcelas',
        ),
        migrations.AddField(
            model_name='ordemdeservico',
            name='parcelas',
            field=models.ManyToManyField(to='diamante.plantio'),
        ),
    ]
