# Generated by Django 5.0 on 2024-03-22 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aviacao', '0009_remove_parametrosaplicacao_parcelas_and_more'),
        ('diamante', '0089_plantio_area_aferida'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tabelapilotos',
            options={'ordering': ['tipo', 'safra', 'ciclo', 'vazao'], 'verbose_name': 'Preço do Piloto', 'verbose_name_plural': 'Preços dos Pilotos'},
        ),
        migrations.AlterUniqueTogether(
            name='tabelapilotos',
            unique_together={('ativo', 'tipo', 'safra', 'ciclo', 'vazao')},
        ),
        migrations.AddField(
            model_name='ordemdeservico',
            name='tarifa_piloto',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='aviacao.tabelapilotos'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ordemdeservico',
            name='data',
            field=models.DateField(verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='ordemdeservico',
            name='data_final',
            field=models.DateField(verbose_name='Data Final Aplicação'),
        ),
        migrations.AlterField(
            model_name='ordemdeservico',
            name='data_inicial',
            field=models.DateField(verbose_name='Data Inicial Aplicação'),
        ),
        migrations.AlterField(
            model_name='parametrosaplicacao',
            name='data_emissao',
            field=models.DateField(verbose_name='Emitido em'),
        ),
    ]
