# Generated by Django 5.0 on 2024-03-22 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aviacao', '0010_alter_tabelapilotos_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordemdeservico',
            name='tempo_aplicacao',
        ),
    ]
