# Generated by Django 5.0 on 2026-05-12 10:58

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('diamante', '0139_plantioextratoarea_kml_area_m2_and_more'),
        ('opscheckin', '0021_opsboardaccess'),
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(help_text='Código interno da máquina. Ex: TR23, 11-0038.', max_length=80, verbose_name='Identificador')),
                ('chassis', models.CharField(blank=True, max_length=120, null=True, verbose_name='Chassi')),
                ('description', models.CharField(max_length=180, verbose_name='Descrição')),
                ('machine_type', models.CharField(choices=[('tractor', 'Trator'), ('sprayer', 'Pulverizador'), ('harvester', 'Colheitadeira'), ('other', 'Outro')], default='tractor', max_length=30, verbose_name='Tipo')),
                ('brand', models.CharField(blank=True, max_length=80, null=True, verbose_name='Marca')),
                ('model_name', models.CharField(blank=True, max_length=80, null=True, verbose_name='Modelo')),
                ('status', models.CharField(choices=[('operation', 'Em operação'), ('maintenance', 'Manutenção'), ('revision', 'Revisão'), ('inactive', 'Inativo')], default='operation', max_length=30, verbose_name='Status')),
                ('current_hourmeter', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=10, verbose_name='Horímetro atual')),
                ('last_hourmeter_at', models.DateTimeField(blank=True, null=True, verbose_name='Última leitura do horímetro')),
                ('last_revision_hourmeter', models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True, verbose_name='Horímetro da última revisão')),
                ('next_revision_hourmeter', models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True, verbose_name='Horímetro da próxima revisão')),
                ('revision_interval_hours', models.DecimalField(decimal_places=1, default=Decimal('250.0'), help_text='Ex: revisão a cada 250 horas.', max_digits=8, verbose_name='Intervalo padrão entre revisões')),
                ('average_hours_per_day', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Usado para estimar quantos dias faltam até a próxima revisão.', max_digits=8, verbose_name='Média de horas por dia')),
                ('location_text', models.CharField(blank=True, max_length=180, null=True, verbose_name='Localidade original')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('fazenda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='machines', to='diamante.fazenda')),
            ],
            options={
                'verbose_name': 'Máquina',
                'verbose_name_plural': 'Máquinas',
                'ordering': ['identifier'],
            },
        ),
        migrations.CreateModel(
            name='HourmeterReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=1, max_digits=10, verbose_name='Horímetro')),
                ('measured_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data da leitura')),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('api', 'API'), ('import', 'Importação'), ('app', 'Aplicativo')], default='manual', max_length=30, verbose_name='Origem')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hourmeter_readings', to='maquinario.machine')),
            ],
            options={
                'verbose_name': 'Leitura de horímetro',
                'verbose_name_plural': 'Leituras de horímetro',
                'ordering': ['-measured_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='MachineAlertRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True, verbose_name='Ativa')),
                ('hours_before', models.DecimalField(decimal_places=1, default=Decimal('30.0'), max_digits=8, verbose_name='Alertar faltando quantas horas')),
                ('days_before', models.PositiveIntegerField(default=7, verbose_name='Alertar faltando quantos dias')),
                ('notify_when_overdue', models.BooleanField(default=True, verbose_name='Avisar quando vencida')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_rules', to='maquinario.machine')),
                ('managers', models.ManyToManyField(blank=True, related_name='machine_alert_rules', to='opscheckin.manager')),
            ],
            options={
                'verbose_name': 'Regra de alerta',
                'verbose_name_plural': 'Regras de alerta',
            },
        ),
        migrations.CreateModel(
            name='MaintenanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_type', models.CharField(choices=[('revision', 'Revisão'), ('corrective', 'Corretiva'), ('preventive', 'Preventiva'), ('other', 'Outra')], default='revision', max_length=30, verbose_name='Tipo')),
                ('performed_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Realizada em')),
                ('hourmeter', models.DecimalField(decimal_places=1, max_digits=10, verbose_name='Horímetro da revisão')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('next_revision_hourmeter', models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True, verbose_name='Próxima revisão no horímetro')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='maquinario.machine')),
            ],
            options={
                'verbose_name': 'Manutenção/Revisão',
                'verbose_name_plural': 'Manutenções/Revisões',
                'ordering': ['-performed_at', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='machine',
            constraint=models.UniqueConstraint(fields=('fazenda', 'identifier'), name='unique_machine_identifier_per_farm'),
        ),
        migrations.AddIndex(
            model_name='hourmeterreading',
            index=models.Index(fields=['machine', '-measured_at'], name='maquinario__machine_b37ced_idx'),
        ),
    ]
