# Generated by Django 5.0 on 2026-05-12 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diamante', '0139_plantioextratoarea_kml_area_m2_and_more'),
        ('maquinario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hourmeterreading',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual'), ('api', 'API'), ('import', 'Importação'), ('app', 'Aplicativo'), ('whatsapp', 'WhatsApp')], default='manual', max_length=30, verbose_name='Origem'),
        ),
        migrations.CreateModel(
            name='MaintenancePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ex: Revisão de 300h, Revisão de 600h.', max_length=120, verbose_name='Nome da revisão')),
                ('machine_type', models.CharField(choices=[('tractor', 'Trator'), ('sprayer', 'Pulverizador'), ('harvester', 'Colheitadeira'), ('other', 'Outro')], default='tractor', max_length=30, verbose_name='Tipo de máquina')),
                ('interval_hours', models.DecimalField(decimal_places=1, help_text='Ex: 300, 600.', max_digits=8, verbose_name='Intervalo em horas')),
                ('description', models.TextField(blank=True, help_text='O que deve ser verificado/trocado nessa revisão.', null=True, verbose_name='Descrição padrão')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('fazenda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_plans', to='diamante.fazenda')),
            ],
            options={
                'verbose_name': 'Plano de manutenção',
                'verbose_name_plural': 'Planos de manutenção',
                'ordering': ['fazenda', 'machine_type', 'interval_hours'],
            },
        ),
        migrations.AddField(
            model_name='maintenancerecord',
            name='maintenance_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_records', to='maquinario.maintenanceplan', verbose_name='Plano de manutenção'),
        ),
        migrations.AddConstraint(
            model_name='maintenanceplan',
            constraint=models.UniqueConstraint(fields=('fazenda', 'machine_type', 'interval_hours'), name='unique_maintenance_plan_per_farm_type_interval'),
        ),
    ]
