# Generated by Django 5.0 on 2026-05-12 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diamante', '0139_plantioextratoarea_kml_area_m2_and_more'),
        ('maquinario', '0002_alter_hourmeterreading_source_maintenanceplan_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maintenanceplan',
            options={'ordering': ['interval_hours', 'name'], 'verbose_name': 'Plano de manutenção', 'verbose_name_plural': 'Planos de manutenção'},
        ),
        migrations.RemoveConstraint(
            model_name='maintenanceplan',
            name='unique_maintenance_plan_per_farm_type_interval',
        ),
        migrations.RemoveField(
            model_name='maintenanceplan',
            name='fazenda',
        ),
        migrations.RemoveField(
            model_name='maintenanceplan',
            name='machine_type',
        ),
        migrations.AddField(
            model_name='maintenanceplan',
            name='farms',
            field=models.ManyToManyField(blank=True, help_text='Fazendas onde essa regra de manutenção pode ser aplicada.', related_name='maintenance_plans', to='diamante.fazenda', verbose_name='Fazendas'),
        ),
        migrations.AddField(
            model_name='maintenanceplan',
            name='machine_types',
            field=models.JSONField(blank=True, default=list, help_text='Lista de tipos: tractor, sprayer, harvester, other.', verbose_name='Tipos de máquina'),
        ),
    ]
