# Generated by Django 5.0 on 2026-05-12 18:24

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maquinario', '0003_alter_maintenanceplan_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='average_hours_per_day',
            field=models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text='Média estimada de trabalho por dia. Usado para calcular dias até a próxima revisão.', max_digits=8, verbose_name='Média de horas por dia'),
        ),
    ]
