# Generated by Django 5.0 on 2026-05-13 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diamante', '0139_plantioextratoarea_kml_area_m2_and_more'),
        ('maquinario', '0004_alter_machine_average_hours_per_day'),
    ]

    operations = [
        migrations.CreateModel(
            name='MachineFarmTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('app', 'Aplicativo'), ('admin', 'Admin'), ('agent', 'Agente'), ('system', 'Sistema')], default='app', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('user_uid', models.CharField(blank=True, max_length=180)),
                ('user_email', models.EmailField(blank=True, max_length=254)),
                ('user_display_name', models.CharField(blank=True, max_length=180)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_fazenda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='machine_transfers_from', to='diamante.fazenda')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farm_transfers', to='maquinario.machine')),
                ('to_fazenda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='machine_transfers_to', to='diamante.fazenda')),
            ],
            options={
                'verbose_name': 'Transferência de Fazenda',
                'verbose_name_plural': 'Transferências de Fazenda',
                'ordering': ['-created_at'],
            },
        ),
    ]
