# Generated by Django 5.0 on 2026-05-13 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maquinario', '0005_machinefarmtransfer'),
    ]

    operations = [
        migrations.AddField(
            model_name='hourmeterreading',
            name='user_display_name',
            field=models.CharField(blank=True, max_length=180, verbose_name='Nome do usuário'),
        ),
        migrations.AddField(
            model_name='hourmeterreading',
            name='user_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='E-mail do usuário'),
        ),
        migrations.AddField(
            model_name='hourmeterreading',
            name='user_uid',
            field=models.CharField(blank=True, max_length=180, verbose_name='UID do usuário'),
        ),
        migrations.AddField(
            model_name='maintenancerecord',
            name='user_display_name',
            field=models.CharField(blank=True, max_length=180, verbose_name='Nome do usuário'),
        ),
        migrations.AddField(
            model_name='maintenancerecord',
            name='user_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='E-mail do usuário'),
        ),
        migrations.AddField(
            model_name='maintenancerecord',
            name='user_uid',
            field=models.CharField(blank=True, max_length=180, verbose_name='UID do usuário'),
        ),
    ]
