# Generated by Django 5.0 on 2026-05-13 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maquinario', '0006_hourmeterreading_user_display_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hourmeterreading',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual'), ('api', 'API'), ('import', 'Importação'), ('app', 'Aplicativo'), ('app_offline', 'Aplicativo offline'), ('whatsapp', 'WhatsApp')], default='manual', max_length=30, verbose_name='Origem'),
        ),
    ]
