# Generated by Django 5.0 on 2026-05-13 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maquinario', '0007_alter_hourmeterreading_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='MachineStatusChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, choices=[('operation', 'Em operação'), ('maintenance', 'Manutenção'), ('revision', 'Revisão'), ('inactive', 'Inativo')], max_length=30, verbose_name='Status anterior')),
                ('to_status', models.CharField(choices=[('operation', 'Em operação'), ('maintenance', 'Manutenção'), ('revision', 'Revisão'), ('inactive', 'Inativo')], max_length=30, verbose_name='Novo status')),
                ('source', models.CharField(choices=[('app', 'Aplicativo'), ('admin', 'Admin'), ('agent', 'Agente'), ('system', 'Sistema')], default='app', max_length=20, verbose_name='Origem')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('user_uid', models.CharField(blank=True, max_length=180)),
                ('user_email', models.EmailField(blank=True, max_length=254)),
                ('user_display_name', models.CharField(blank=True, max_length=180)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_changes', to='maquinario.machine')),
            ],
            options={
                'verbose_name': 'Alteração de status da máquina',
                'verbose_name_plural': 'Alterações de status das máquinas',
                'ordering': ['-created_at'],
            },
        ),
    ]
