# Generated by Django 5.0 on 2026-05-13 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maquinario', '0008_machinestatuschange'),
        ('opscheckin', '0022_alter_outboundmessage_kind'),
    ]

    operations = [
        migrations.CreateModel(
            name='MachineWhatsappCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('update_hourmeter', 'Atualizar horímetro'), ('register_revision', 'Registrar revisão')], db_index=True, max_length=40)),
                ('status', models.CharField(choices=[('pending_confirmation', 'Aguardando confirmação'), ('applied', 'Aplicado'), ('cancelled', 'Cancelado'), ('failed', 'Falhou')], db_index=True, default='pending_confirmation', max_length=40)),
                ('original_text', models.TextField(blank=True, default='')),
                ('parsed_payload', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True, default='')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applied_hourmeter_reading', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_commands', to='maquinario.hourmeterreading')),
                ('applied_maintenance_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_commands', to='maquinario.maintenancerecord')),
                ('inbound_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='machine_commands', to='opscheckin.inboundmessage')),
                ('machine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_commands', to='maquinario.machine')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='machine_whatsapp_commands', to='opscheckin.manager')),
            ],
            options={
                'verbose_name': 'Comando WhatsApp de máquina',
                'verbose_name_plural': 'Comandos WhatsApp de máquinas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MachineMaintenanceAlertDispatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_date', models.DateField(db_index=True)),
                ('hours_to_next_revision', models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('provider_message_id', models.CharField(blank=True, default='', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_alert_dispatches', to='maquinario.machine')),
                ('maintenance_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alert_dispatches', to='maquinario.maintenanceplan')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machine_alert_dispatches', to='opscheckin.manager')),
            ],
            options={
                'verbose_name': 'Disparo de alerta de revisão',
                'verbose_name_plural': 'Disparos de alertas de revisão',
                'ordering': ['-reference_date', 'machine__identifier'],
                'indexes': [models.Index(fields=['manager', 'reference_date'], name='maquinario__manager_533142_idx'), models.Index(fields=['machine', 'reference_date'], name='maquinario__machine_badd54_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='machinemaintenancealertdispatch',
            constraint=models.UniqueConstraint(fields=('manager', 'machine', 'maintenance_plan', 'reference_date'), name='uniq_machine_alert_dispatch_day'),
        ),
        migrations.AddIndex(
            model_name='machinewhatsappcommand',
            index=models.Index(fields=['manager', 'status', 'created_at'], name='maquinario__manager_a6a3f4_idx'),
        ),
        migrations.AddIndex(
            model_name='machinewhatsappcommand',
            index=models.Index(fields=['machine', 'created_at'], name='maquinario__machine_707d68_idx'),
        ),
        migrations.AddIndex(
            model_name='machinewhatsappcommand',
            index=models.Index(fields=['action', 'status'], name='maquinario__action_023a09_idx'),
        ),
    ]
