# Generated by Django 5.0 on 2026-05-14 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maquinario', '0009_machinewhatsappcommand_and_more'),
        ('opscheckin', '0023_alter_outboundmessage_kind'),
    ]

    operations = [
        migrations.CreateModel(
            name='MachineHourmeterStaleAlertDispatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audience', models.CharField(choices=[('update_manager', 'Responsável por atualização'), ('field_manager', 'Gerente de Campo')], db_index=True, max_length=30)),
                ('reference_date', models.DateField(db_index=True)),
                ('last_hourmeter_at', models.DateTimeField(blank=True, null=True)),
                ('current_hourmeter', models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('provider_message_id', models.CharField(blank=True, default='', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hourmeter_stale_dispatches', to='maquinario.machine')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machine_hourmeter_stale_dispatches', to='opscheckin.manager')),
            ],
            options={
                'verbose_name': 'Disparo de alerta de horímetro desatualizado',
                'verbose_name_plural': 'Disparos de alertas de horímetro desatualizado',
                'ordering': ['-reference_date', 'machine__identifier'],
                'indexes': [models.Index(fields=['manager', 'reference_date'], name='maquinario__manager_92acec_idx'), models.Index(fields=['machine', 'reference_date'], name='maquinario__machine_458e26_idx'), models.Index(fields=['audience', 'reference_date'], name='maquinario__audienc_07419c_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='machinehourmeterstalealertdispatch',
            constraint=models.UniqueConstraint(fields=('manager', 'machine', 'audience', 'reference_date'), name='uniq_machine_hourmeter_stale_alert_day'),
        ),
    ]
