# Generated by Django 4.1.7 on 2023-04-01 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diamante', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ciclo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criados', models.DateTimeField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('ciclo', models.PositiveBigIntegerField(help_text='Ciclo', unique=True, verbose_name='ciclo')),
            ],
            options={
                'verbose_name': 'Ciclo',
                'verbose_name_plural': 'Ciclos',
                'ordering': ['ciclo'],
            },
        ),
        migrations.AlterField(
            model_name='safra',
            name='safra',
            field=models.CharField(help_text='Safra', max_length=100, unique=True, verbose_name='Safra'),
        ),
    ]
