# Generated by Django 4.1.7 on 2023-04-01 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diamante', '0003_alter_projeto_nome_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='talhao',
            name='modulo',
            field=models.CharField(blank=True, help_text='Módulo do Talhão', max_length=20, null=True, verbose_name='Módulo'),
        ),
    ]
