# Generated by Django 4.1.7 on 2023-04-03 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diamante', '0010_alter_talhao_options'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='plantio',
            unique_together={('safra', 'ciclo', 'talhao')},
        ),
    ]
