# Generated by Django 4.1.7 on 2023-04-03 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diamante', '0011_alter_plantio_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantio',
            name='fazenda',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='diamante.projeto'),
            preserve_default=False,
        ),
    ]
