# Generated by Django 4.1.7 on 2023-04-03 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diamante', '0012_plantio_fazenda'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='talhao',
            options={'verbose_name': 'Talhao', 'verbose_name_plural': 'Talhoes'},
        ),
        migrations.AlterOrderWithRespectTo(
            name='talhao',
            order_with_respect_to='fazenda',
        ),
    ]
