# Generated by Django 4.1.7 on 2023-04-03 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diamante', '0013_alter_talhao_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plantio',
            name='fazenda',
        ),
    ]
