# Generated by Django 4.1.7 on 2023-04-11 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diamante', '0017_alter_plantio_talhao'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantio',
            name='area_aproveito',
            field=models.BooleanField(default=False, help_text='Apontar caso seja Area de Aproveito', verbose_name='Area Aproveito'),
        ),
    ]
