# Generated by Django 4.1.7 on 2023-04-13 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diamante', '0020_alter_operacao_options_alter_programa_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='operacao',
            options={'ordering': ['programa', 'operacao_numero'], 'verbose_name': 'Programa - Operação', 'verbose_name_plural': 'Programas - Operações'},
        ),
        migrations.AddField(
            model_name='programa',
            name='nome_fantasia',
            field=models.CharField(blank=True, help_text='Nome Fantasia do Programa', max_length=40, null=True, verbose_name='Nome Fantasia Programa'),
        ),
        migrations.AlterField(
            model_name='plantio',
            name='area_aproveito',
            field=models.BooleanField(default=False, help_text='Apontar caso seja Area de Aproveito', verbose_name='Area Aprov.'),
        ),
        migrations.AlterField(
            model_name='plantio',
            name='area_parcial',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Area Parcial / ha', max_digits=8, null=True, verbose_name='Area P. Colhida'),
        ),
    ]
