# Generated by Django 4.1.7 on 2023-04-14 08:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('diamante', '0021_alter_operacao_options_programa_nome_fantasia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantio',
            name='data_plantio',
            field=models.DateField(default=django.utils.timezone.now, help_text='dd/mm/aaaa'),
        ),
    ]
