# Generated by Django 4.1.7 on 2023-04-14 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diamante', '0022_alter_plantio_data_plantio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Defensivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criados', models.DateTimeField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('produto', models.CharField(max_length=140, verbose_name='Descrição Defensivo')),
                ('unidade_medida', models.CharField(choices=[('LT', 'l_ha'), ('KG', 'kg_ha')], max_length=20, verbose_name='Unidade de Medida')),
                ('formulacao', models.CharField(choices=[('liquido', 'Líquido'), ('solido', 'Sólido')], max_length=40, verbose_name='Formulação')),
                ('tipo', models.CharField(choices=[('acaricida', 'Acaricida'), ('adjuvante', 'Adjuvante'), ('biologico', 'Biológico'), ('fertilizante', 'Fertilizante'), ('fungicida', 'Fungicida'), ('herbicida', 'Herbicida'), ('inseticida', 'Inseticida'), ('nutricao', 'Nutrição'), ('oleo_mineral_vegetal', 'Óleo Mineral/Vegetal'), ('regulador', 'Regulador')], max_length=40, verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Defensivo',
                'verbose_name_plural': 'Defensivos',
                'ordering': ['produto'],
            },
        ),
    ]
