# Generated by Django 4.1.7 on 2023-04-14 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diamante', '0023_defensivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defensivo',
            name='unidade_medida',
            field=models.CharField(choices=[('l_ha', 'LT'), ('kg_ha', 'KG')], max_length=20, verbose_name='Unidade de Medida'),
        ),
    ]
