# Generated by Django 4.1.7 on 2023-04-14 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diamante', '0025_plantio_data_prevista_plantio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plantio',
            name='data_programa_1',
        ),
        migrations.RemoveField(
            model_name='plantio',
            name='data_programa_2',
        ),
    ]
