# Generated by Django 4.1.7 on 2023-04-14 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diamante', '0026_remove_plantio_data_programa_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defensivo',
            name='produto',
            field=models.CharField(max_length=140, unique=True, verbose_name='Descrição Defensivo'),
        ),
    ]
