# Generated by Django 4.1.7 on 2023-04-14 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diamante', '0027_alter_defensivo_produto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aplicacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criados', models.DateTimeField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('dose', models.DecimalField(decimal_places=3, help_text='Dose aplicada de Kg ou Lt por ha.', max_digits=8, verbose_name='Dose KG/LT por ha')),
                ('obs', models.TextField(blank=True, max_length=500, verbose_name='Observação')),
                ('defensivo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='diamante.defensivo')),
                ('operacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='diamante.operacao')),
            ],
            options={
                'verbose_name': 'Aplicação de Operações/Programas',
                'verbose_name_plural': 'Aplicações de Operações/Programas',
                'ordering': ['operacao', 'defensivo'],
            },
        ),
        migrations.DeleteModel(
            name='Aplicacoes',
        ),
    ]
