# Generated by Django 4.1.7 on 2023-04-14 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diamante', '0028_aplicacao_delete_aplicacoes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aplicacao',
            options={'ordering': ['operacao', 'defensivo'], 'verbose_name': 'Programa - Operações/Aplicações', 'verbose_name_plural': 'Programas - Operações/Aplicações'},
        ),
    ]
