# Generated by Django 4.1.7 on 2023-04-17 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diamante', '0029_alter_aplicacao_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operacao',
            name='obs_1',
        ),
        migrations.RemoveField(
            model_name='operacao',
            name='obs_2',
        ),
        migrations.AddField(
            model_name='plantio',
            name='data_prevista_colheita',
            field=models.DateField(blank=True, help_text='dd/mm/aaaa - Data Projetada para a Colheita', null=True),
        ),
        migrations.AlterField(
            model_name='plantio',
            name='finalizado_colheita',
            field=models.BooleanField(default=False, help_text='Finalizada a Colheita', verbose_name='Finalizado Colheita'),
        ),
        migrations.AlterField(
            model_name='plantio',
            name='finalizado_plantio',
            field=models.BooleanField(default=True, help_text='Finalizado o Plantio', verbose_name='Finalizado Plantio'),
        ),
    ]
