# Generated by Django 4.1.7 on 2023-04-17 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diamante', '0030_remove_operacao_obs_1_remove_operacao_obs_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='id_farmbox',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='ID_D'),
        ),
        migrations.AddField(
            model_name='variedade',
            name='id_farmbox',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='ID_D'),
        ),
    ]
