# Generated by Django 4.1.7 on 2023-04-17 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diamante', '0031_projeto_id_farmbox_variedade_id_farmbox'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='id_farmbox',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='ID FarmBox'),
        ),
        migrations.AlterField(
            model_name='variedade',
            name='id_farmbox',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='ID FarmBox'),
        ),
    ]
