# Generated by Django 4.1.7 on 2023-04-18 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diamante', '0032_alter_projeto_id_farmbox_alter_variedade_id_farmbox'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aplicacao',
            name='operacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='programa_related_aplicacao', to='diamante.operacao'),
        ),
    ]
