# Generated by Django 4.1.7 on 2023-04-19 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diamante', '0033_alter_aplicacao_operacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='operacao',
            name='base_operacao_anterior',
            field=models.BooleanField(default=False, help_text='Infomrar se esta operação tem como base a data de aplicação da Operação anterior', verbose_name='Base ültima Operação'),
        ),
        migrations.AddField(
            model_name='operacao',
            name='dias_base_operacao_anterior',
            field=models.IntegerField(blank=True, null=True, verbose_name='Dias de Janela Após a aplicação anterior'),
        ),
    ]
