# Generated by Django 4.1.7 on 2023-04-19 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diamante', '0034_operacao_base_operacao_anterior_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cultura',
            name='id_farmbox',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='ID FarmBox'),
        ),
    ]
