# Generated by Django 4.1.7 on 2023-05-01 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diamante', '0036_programa_end_date_programa_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantio',
            name='finalizado_plantio',
            field=models.BooleanField(default=False, help_text='Finalizado o Plantio', verbose_name='Finalizado Plantio'),
        ),
    ]
