# Generated by Django 4.1.7 on 2023-05-02 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diamante', '0037_alter_plantio_finalizado_plantio'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='capacidade_plantio_ha_dia',
            field=models.PositiveIntegerField(default=50, help_text='Capacidade Projetada Plantio ha/dia', verbose_name='Quantidade ha Plantio / dia'),
        ),
    ]
