# Generated by Django 4.1.7 on 2023-05-11 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diamante', '0040_alter_defensivo_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantio',
            name='variedade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='diamante.variedade'),
        ),
    ]
