# Generated by Django 4.1.7 on 2023-05-27 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diamante', '0042_plantio_cronograma_programa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantio',
            name='cronograma_programa',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
