# Generated by Django 4.1.7 on 2023-06-18 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diamante', '0044_alter_ciclo_options_alter_safra_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantio',
            name='map_centro_id',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plantio',
            name='map_geo_points',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
