# Generated by Django 4.1.7 on 2023-06-18 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diamante', '0045_plantio_map_centro_id_plantio_map_geo_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='cultura',
            name='map_color',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True, verbose_name='Cor no Mapa'),
        ),
        migrations.AddField(
            model_name='variedade',
            name='map_oppacity',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Opacidade no Mapa'),
        ),
    ]
