# Generated by Django 4.1.7 on 2023-06-18 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diamante', '0046_cultura_map_color_variedade_map_oppacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='operacao',
            name='map_color',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Cor no Mapa'),
        ),
    ]
