# Generated by Django 4.1.7 on 2023-06-18 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diamante', '0048_projeto_map_centro_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cultura',
            name='map_color_line',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True, verbose_name='Cor do Contorno no Mapa'),
        ),
    ]
