# Generated by Django 4.1.7 on 2023-07-28 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diamante', '0050_projeto_map_zoom'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantio',
            name='plantio_descontinuado',
            field=models.BooleanField(default=False, help_text='Plantio interrompido ?', verbose_name='Plantio Descontinuado'),
        ),
    ]
