# Generated by Django 4.1.7 on 2023-08-01 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diamante', '0051_plantio_plantio_descontinuado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colheita',
            name='peso_umido',
        ),
        migrations.AddField(
            model_name='colheita',
            name='impureza',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Informa a impureza da Carga', max_digits=4, null=True, verbose_name='Impureza'),
        ),
        migrations.AddField(
            model_name='colheita',
            name='op',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='OP'),
        ),
        migrations.AddField(
            model_name='colheita',
            name='peso_bruto',
            field=models.PositiveIntegerField(default=0, help_text='Informe o Peso Bruto do Veículo', verbose_name='Peso Bruto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='colheita',
            name='peso_tara',
            field=models.PositiveIntegerField(default=0, help_text='Informe o Peso Tara do Veículo', verbose_name='Peso Tara'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='colheita',
            name='ticket',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Ticket'),
        ),
        migrations.AddField(
            model_name='colheita',
            name='umidade',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Informa a Umidade da Carga', max_digits=4, null=True, verbose_name='Umidade'),
        ),
        migrations.AlterField(
            model_name='colheita',
            name='peso_liquido',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Peso Líquido Calculado', max_digits=8, null=True, verbose_name='Peso Liquido'),
        ),
    ]
