# Generated by Django 4.1.7 on 2023-08-01 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diamante', '0052_remove_colheita_peso_umido_colheita_impureza_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposito',
            name='nome_fantasia',
            field=models.CharField(blank=True, help_text='Depósito / Fantasia', max_length=100, null=True, unique=True, verbose_name='Nome Fantasia'),
        ),
    ]
