# Generated by Django 4.1.7 on 2023-08-01 15:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diamante', '0054_colheita_peso_scs_liquido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colheita',
            name='placa',
            field=models.CharField(help_text='Placa do Veículo', max_length=7, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Somente letras e números permitido.'), django.core.validators.MinLengthValidator(7)], verbose_name='Placa'),
        ),
    ]
