# Generated by Django 4.1.7 on 2023-08-01 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diamante', '0055_alter_colheita_placa'),
    ]

    operations = [
        migrations.AddField(
            model_name='colheita',
            name='desconto_impureza',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Desconto Impureza Calculado', max_digits=8, null=True, verbose_name='Desc. Impureza'),
        ),
        migrations.AddField(
            model_name='colheita',
            name='desconto_umidade',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Desconto Umidade Calculado', max_digits=8, null=True, verbose_name='Desc. Umidade'),
        ),
    ]
