# Generated by Django 4.1.7 on 2023-08-01 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diamante', '0056_colheita_desconto_impureza_colheita_desconto_umidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colheita',
            name='impureza',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Informe a impureza da Carga', max_digits=4, null=True, verbose_name='Impureza'),
        ),
        migrations.AlterField(
            model_name='colheita',
            name='umidade',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Informe a Umidade da Carga', max_digits=4, null=True, verbose_name='Umidade'),
        ),
    ]
