# Generated by Django 4.1.7 on 2023-08-02 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diamante', '0057_alter_colheita_impureza_alter_colheita_umidade'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='colheita',
            unique_together={('plantio', 'romaneio', 'ticket')},
        ),
    ]
