# Generated by Django 4.1.7 on 2023-08-07 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diamante', '0058_alter_colheita_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantioDetail',
            fields=[
            ],
            options={
                'verbose_name': 'Plantio - Resumo',
                'verbose_name_plural': 'Plantios - Resumo',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('diamante.plantio',),
        ),
        migrations.AlterField(
            model_name='colheita',
            name='plantio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plantio_colheita', to='diamante.plantio'),
        ),
    ]
