# Generated by Django 4.1.7 on 2023-08-17 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diamante', '0061_alter_defensivo_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='colheita',
            name='bandinha',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Informe a Bandinha da Carga', max_digits=4, null=True, verbose_name='Bandinha'),
        ),
        migrations.AddField(
            model_name='colheita',
            name='desconto_bandinha',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Desconto Bandinha Calculado', max_digits=8, null=True, verbose_name='Desc. Bandinha'),
        ),
    ]
