# Generated by Django 4.1.7 on 2023-10-02 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diamante', '0064_plantiodetailplantio_alter_plantiodetail_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='colheita',
            name='peso_scs_limpo_e_seco',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Peso Limpo e Seco Calculado em Sacos de 60Kg', max_digits=8, null=True, verbose_name='Sacos Limpo e Seco'),
        ),
    ]
