# Generated by Django 4.1.7 on 2023-10-08 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diamante', '0066_alter_defensivo_tipo'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='plantio',
            index=models.Index(fields=['safra', 'ciclo', 'talhao', 'programa', 'variedade', 'data_plantio'], name='diamante_pl_safra_i_53655c_idx'),
        ),
    ]
