# Generated by Django 4.1.7 on 2023-10-08 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diamante', '0067_plantio_diamante_pl_safra_i_53655c_idx'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='ciclo',
            index=models.Index(fields=['ciclo'], name='diamante_ci_ciclo_9c2afd_idx'),
        ),
        migrations.AddIndex(
            model_name='cultura',
            index=models.Index(fields=['cultura'], name='diamante_cu_cultura_2526fa_idx'),
        ),
        migrations.AddIndex(
            model_name='programa',
            index=models.Index(fields=['nome'], name='diamante_pr_nome_196704_idx'),
        ),
        migrations.AddIndex(
            model_name='safra',
            index=models.Index(fields=['safra'], name='diamante_sa_safra_e83578_idx'),
        ),
        migrations.AddIndex(
            model_name='variedade',
            index=models.Index(fields=['variedade'], name='diamante_va_varieda_a5c0d7_idx'),
        ),
    ]
