# Generated by Django 4.1.7 on 2023-10-11 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diamante', '0068_ciclo_diamante_ci_ciclo_9c2afd_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AplicacaoPlantio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criados', models.DateTimeField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('dose', models.DecimalField(decimal_places=3, help_text='Dose aplicada de Kg ou Lt por ha.', max_digits=8, verbose_name='Dose KG/LT por ha')),
                ('data_prevista', models.DateField(blank=True, help_text='dd/mm/aaaa - Data Prevista Aplicação', null=True)),
                ('aplicado', models.BooleanField(default=False, help_text='Informar se a Aplicação foi realizada', verbose_name='Aplicação Efetuada')),
                ('obs', models.TextField(blank=True, max_length=500, verbose_name='Observação')),
                ('defensivo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='diamante.defensivo')),
                ('estagio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='diamante.operacao')),
                ('plantio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='diamante.plantio')),
            ],
            options={
                'verbose_name': 'Aplicação Plantio',
                'verbose_name_plural': 'Aplicações Plantio',
                'unique_together': {('plantio', 'estagio', 'defensivo')},
            },
        ),
    ]
