# Generated by Django 4.1.7 on 2023-11-06 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diamante', '0072_programa_versao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programa',
            name='versao',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='Versão Atual'),
        ),
    ]
