# Generated by Django 4.1.7 on 2023-11-10 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diamante', '0073_alter_programa_versao'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantio',
            name='id_farmbox',
            field=models.PositiveIntegerField(blank=True, help_text='Id de cada plantio do farmbox', null=True, unique=True, verbose_name='ID Plantio Farmbox'),
        ),
    ]
