# Generated by Django 4.1.7 on 2023-11-16 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diamante', '0074_plantio_id_farmbox'),
    ]

    operations = [
        migrations.CreateModel(
            name='CicloAtual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criados', models.DateTimeField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('nome', models.CharField(blank=True, max_length=150, null=True, verbose_name='Safra / Ciclo Atual')),
                ('ciclo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='diamante.ciclo')),
                ('safra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='diamante.safra')),
            ],
            options={
                'verbose_name': 'Safra - Ciclo Atual',
                'verbose_name_plural': 'Safra - Ciclo Atuais',
            },
        ),
    ]
