# Generated by Django 4.1.7 on 2023-11-20 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diamante', '0076_plannerplantio'),
    ]

    operations = [
        migrations.AddField(
            model_name='plannerplantio',
            name='variedade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='diamante.variedade'),
        ),
        migrations.AlterField(
            model_name='plannerplantio',
            name='start_date',
            field=models.DateField(blank=True, help_text='Data Prevista Início Programa / Plantio', null=True),
        ),
    ]
