# Generated by Django 4.1.7 on 2023-12-06 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diamante', '0077_plannerplantio_variedade_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fazenda',
            options={'ordering': ['nome'], 'verbose_name': 'Fazenda', 'verbose_name_plural': 'Fazendas'},
        ),
        migrations.AlterModelOptions(
            name='projeto',
            options={'ordering': ['nome'], 'verbose_name': 'Projeto', 'verbose_name_plural': 'Projetos'},
        ),
        migrations.AlterField(
            model_name='colheita',
            name='ticket',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Ticket'),
        ),
    ]
