# Generated by Django 4.1.7 on 2023-12-09 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diamante', '0078_alter_fazenda_options_alter_projeto_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colheita',
            name='deposito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deposito_colheita', to='diamante.deposito'),
        ),
    ]
