# Generated by Django 5.0 on 2023-12-28 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diamante', '0080_aplicacao_observacao_aplicacaoplantio_observacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantio',
            name='replantio',
            field=models.BooleanField(default=False, help_text='Apontar caso tenha ocorrido replantio nesta Parcela / Safra / Ciclo', verbose_name='Replantio'),
        ),
        migrations.AddField(
            model_name='plantio',
            name='talhao_desativado',
            field=models.BooleanField(default=False, help_text='Apontar caso a Parcela tenha sido desativada nesta Safra / Ciclo', verbose_name='Parcela Desativada'),
        ),
    ]
