# Generated by Django 5.0 on 2023-12-28 15:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("diamante", "0081_plantio_replantio_plantio_talhao_desativado"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="aplicacao",
            unique_together={("operacao", "defensivo", "ativo", "dose")},
        ),
    ]
