# Generated by Django 5.0 on 2024-01-08 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diamante', '0082_alter_aplicacao_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criados', models.DateTimeField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('data', models.DateTimeField(verbose_name='Data Visita')),
                ('resp_visita', models.CharField(blank=True, help_text='Pessoa que foi visitar a fazenda', max_length=100, null=True, verbose_name='Responsável pela Visita')),
                ('resp_fazenda', models.CharField(blank=True, help_text='Pessoa que foi receber a visita na fazenda', max_length=100, null=True, verbose_name='Responsável Recebedor da Fazenda')),
                ('observacoes_gerais', models.TextField(blank=True, null=True, verbose_name='Observações Gerais')),
                ('fazenda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='diamante.fazenda')),
                ('projeto', models.ManyToManyField(blank=True, null=True, to='diamante.projeto')),
            ],
            options={
                'verbose_name': 'Visita',
                'verbose_name_plural': 'Visitas',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='RegistroVisitas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criados', models.DateTimeField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('image', models.ImageField(upload_to='visitas/', verbose_name='Imagem')),
                ('image_title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Título da Imagem')),
                ('obs', models.TextField(blank=True, null=True, verbose_name='Obs')),
                ('visita', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='diamante.visitas')),
            ],
            options={
                'verbose_name': 'Registro da Visita',
                'verbose_name_plural': 'Registros da Visita',
                'ordering': ['criados'],
            },
        ),
    ]
