# Generated by Django 5.0 on 2024-01-08 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diamante', '0083_visitas_registrovisitas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitas',
            name='data',
            field=models.DateField(help_text='dd/mm/aaaa - Data efetiva da Visita', verbose_name='Data Visita'),
        ),
    ]
