# Generated by Django 5.0 on 2024-01-12 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diamante', '0085_alter_registrovisitas_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrovisitas',
            name='image_link_url',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Link da Imagem'),
        ),
    ]
