# Generated by Django 5.0 on 2024-01-12 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diamante', '0086_registrovisitas_image_link_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrovisitas',
            name='image_link_url',
            field=models.URLField(blank=True, max_length=250, null=True, verbose_name='Link da Imagem'),
        ),
    ]
