# Generated by Django 5.0 on 2024-01-23 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diamante', '0087_alter_registrovisitas_image_link_url'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='visitas',
            unique_together=set(),
        ),
    ]
