# Generated by Django 5.0 on 2024-02-24 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diamante', '0088_alter_visitas_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantio',
            name='area_aferida',
            field=models.BooleanField(default=False, help_text='Informa se houve a medição da área após o plantio', verbose_name='Área Aferida'),
        ),
    ]
