# Generated by Django 5.0 on 2024-04-05 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diamante', '0089_plantio_area_aferida'),
    ]

    operations = [
        migrations.AddField(
            model_name='colheita',
            name='id_farmtruck',
            field=models.CharField(blank=True, help_text='Id de cada plantio do App FarmTruck', max_length=100, null=True, verbose_name='ID Plantio Farmtruck APP'),
        ),
    ]
