# Generated by Django 5.0 on 2024-04-18 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diamante', '0090_colheita_id_farmtruck'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='colheita',
            unique_together={('plantio', 'romaneio', 'ticket'), ('romaneio', 'plantio'), ('ticket', 'plantio')},
        ),
        migrations.AlterField(
            model_name='colheita',
            name='id_farmtruck',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ID Plantio Farmtruck APP'),
        ),
    ]
