# Generated by Django 5.0 on 2024-05-21 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diamante', '0092_fazenda_id_encarregado_farmbox_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defensivo',
            name='tipo',
            field=models.CharField(choices=[('acaricida', 'Acaricida'), ('adjuvante', 'Adjuvante'), ('biologico', 'Biológico'), ('cobertura', 'Cobertura'), ('fertilizante', 'Fertilizante'), ('fungicida', 'Fungicida'), ('herbicida', 'Herbicida'), ('inseticida', 'Inseticida'), ('lubrificante', 'Lubrificante'), ('nutricao', 'Nutrição'), ('oleo_mineral_vegetal', 'Óleo Mineral/Vegetal'), ('operacao', 'Operação'), ('protetor', 'Protetor'), ('regulador', 'Regulador'), ('semente', 'Semente')], max_length=40, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='defensivo',
            name='unidade_medida',
            field=models.CharField(choices=[('l_ha', 'LT'), ('kg_ha', 'KG'), ('un_ha', 'Hectare')], max_length=20, verbose_name='Unidade de Medida'),
        ),
    ]
