# Generated by Django 5.0 on 2024-05-21 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diamante', '0093_alter_defensivo_tipo_alter_defensivo_unidade_medida'),
    ]

    operations = [
        migrations.AddField(
            model_name='defensivo',
            name='id_farmbox',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='ID FarmBox'),
        ),
    ]
