# Generated by Django 5.0 on 2024-05-22 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diamante', '0095_alter_defensivo_formulacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defensivo',
            name='id_farmbox',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID FarmBox'),
        ),
        migrations.AlterField(
            model_name='fazenda',
            name='id_encarregado_farmbox',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID Encarregado FarmBox'),
        ),
        migrations.AlterField(
            model_name='fazenda',
            name='id_responsavel_farmbox',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID Responsavel FarmBox'),
        ),
    ]
