# Generated by Django 5.0 on 2024-06-03 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diamante', '0096_alter_defensivo_id_farmbox_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppFarmboxIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criados', models.DateTimeField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('app', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Aps Integração',
                'verbose_name_plural': 'Aps Integrações',
            },
        ),
    ]
