# Generated by Django 5.0 on 2024-06-03 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diamante', '0097_appfarmboxintegration'),
    ]

    operations = [
        migrations.AddField(
            model_name='appfarmboxintegration',
            name='app_fazenda',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Fazenda AP'),
        ),
        migrations.AddField(
            model_name='appfarmboxintegration',
            name='app_nuumero',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='AP Número'),
        ),
    ]
