# Generated by Django 5.0 on 2024-06-20 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diamante', '0098_appfarmboxintegration_app_fazenda_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantio',
            name='area_planejamento_plantio',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Area Planejada / ha', max_digits=8, null=True, verbose_name='Area Planejada para o Plantio'),
        ),
    ]
