# Generated by Django 5.0 on 2024-08-07 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diamante', '0099_plantio_area_planejamento_plantio'),
    ]

    operations = [
        migrations.CreateModel(
            name='StProtheusIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criados', models.DateTimeField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('st_numero', models.CharField(blank=True, max_length=200, null=True, verbose_name='AP Número')),
                ('st_fazenda', models.CharField(blank=True, max_length=200, null=True, verbose_name='Fazenda AP')),
                ('app', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'ST Integração',
                'verbose_name_plural': 'STs Integrações',
            },
        ),
    ]
