# Generated by Django 5.0 on 2024-08-15 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diamante', '0100_stprotheusintegration'),
    ]

    operations = [
        migrations.AddField(
            model_name='cultura',
            name='id_protheus_planejamento',
            field=models.CharField(blank=True, help_text=' ID Cultura Planejamento Agrícola Protheus', max_length=20, null=True, verbose_name='ID Cultura'),
        ),
        migrations.AlterField(
            model_name='stprotheusintegration',
            name='app',
            field=models.JSONField(blank=True, null=True, verbose_name='Detalhes'),
        ),
        migrations.AlterField(
            model_name='stprotheusintegration',
            name='st_fazenda',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Fazenda ST'),
        ),
        migrations.AlterField(
            model_name='stprotheusintegration',
            name='st_numero',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='ST Número'),
        ),
    ]
