# Generated by Django 5.0 on 2024-08-15 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diamante', '0101_cultura_id_protheus_planejamento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='variedade',
            name='id_protheus_planejamento_second_option',
            field=models.CharField(blank=True, help_text=' ID Cultura/Variedade Planejamento Agrícola Protheus', max_length=20, null=True, verbose_name='ID Cultura/Variedade'),
        ),
    ]
