# Generated by Django 5.0 on 2024-08-17 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diamante', '0102_variedade_id_protheus_planejamento_second_option'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColheitaPlantioExtratoArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criados', models.DateTimeField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('area_colhida', models.DecimalField(blank=True, decimal_places=2, help_text='Area Parcial Colhida', max_digits=8, null=True, verbose_name='Area Colhida')),
                ('data_colheita', models.DateField(blank=True, help_text='dd/mm/aaaa - Data Efetiva de Colheita', null=True)),
                ('plantio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='diamante.plantio')),
            ],
            options={
                'verbose_name': 'Extrato da Colheita',
                'verbose_name_plural': 'Extrato das Colheitas',
                'ordering': ['data_colheita', 'plantio'],
            },
        ),
        migrations.CreateModel(
            name='PlantioExtratoArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criados', models.DateTimeField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('area_plantada', models.DecimalField(blank=True, decimal_places=2, help_text='Area Parcial Plantada', max_digits=8, null=True, verbose_name='Area plantada')),
                ('data_plantio', models.DateField(blank=True, help_text='dd/mm/aaaa - Data Efetiva de Plantio', null=True)),
                ('plantio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='diamante.plantio')),
            ],
            options={
                'verbose_name': 'Extrato do Plantio',
                'verbose_name_plural': 'Extrato dos Plantios',
                'ordering': ['data_plantio', 'plantio'],
            },
        ),
    ]
