# Generated by Django 5.0 on 2024-08-20 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diamante', '0105_remove_cultura_id_cultura_dif_protheus_planejamento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeaderPlanejamentoAgricola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criados', models.DateTimeField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('codigo_planejamento', models.CharField(max_length=200, verbose_name='Código do Planejamento')),
                ('ciclo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='diamante.ciclo')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='diamante.projeto')),
                ('safra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='diamante.safra')),
            ],
            options={
                'verbose_name': 'Header Planejamento Agrícola',
                'verbose_name_plural': 'Headers Planejamentos Agrícola',
            },
        ),
    ]
