# Generated by Django 5.0 on 2024-08-20 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diamante', '0107_alter_headerplanejamentoagricola_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='colheitaplantioextratoarea',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='colheitaplantioextratoarea',
            unique_together={('time', 'data_colheita', 'plantio')},
        ),
    ]
