# Generated by Django 5.0 on 2024-09-18 14:18

import diamante.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diamante', '0108_colheitaplantioextratoarea_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criados', models.DateTimeField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('quantidade_comprada', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Quantidade Comprada em Kg')),
                ('sit_pago', models.BooleanField(default=False, verbose_name='Satus Pagamento')),
                ('data_pagamento', models.DateField(blank=True, null=True, verbose_name='Data Pagamento')),
                ('nota_fiscal', models.CharField(blank=True, max_length=255, null=True, verbose_name='Número da Nota Fiscal')),
                ('nf_file', models.FileField(blank=True, null=True, upload_to=diamante.models.get_nf_path, verbose_name='NF')),
                ('fornecedor', models.CharField(blank=True, max_length=255, null=True, verbose_name='Fornecedor')),
                ('defensivo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='diamante.defensivo')),
                ('fazenda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='diamante.fazenda')),
                ('projeto', models.ManyToManyField(blank=True, null=True, to='diamante.projeto')),
            ],
            options={
                'verbose_name': 'Produto Comprado',
                'verbose_name_plural': 'Produtos Comprados',
                'ordering': ['defensivo'],
            },
        ),
    ]
