# Generated by Django 5.0 on 2024-09-24 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diamante', '0109_buyproducts'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantioextratoarea',
            name='aguardando_chuva',
            field=models.BooleanField(default=False, help_text='Apontar caso o Plantio esteja aguardando a chuva', verbose_name='Plantio Aguardando a chuva'),
        ),
    ]
