# Generated by Django 5.0 on 2024-09-27 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diamante', '0110_plantioextratoarea_aguardando_chuva'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyproducts',
            name='nr_pedido',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Número do pedido'),
        ),
    ]
