# Generated by Django 5.0 on 2024-10-03 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diamante', '0111_buyproducts_nr_pedido'),
    ]

    operations = [
        migrations.CreateModel(
            name='SentSeeds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criados', models.DateTimeField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('data_envio', models.DateField(blank=True, help_text='dd/mm/aaaa - Data Envio da Semente', null=True)),
                ('quantidade_bags', models.IntegerField(blank=True, null=True, verbose_name='Quantidade de Bags Enviados')),
                ('peso_bag', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Peso dos Bags Enviados em Kg')),
                ('peso_total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Peso total da carga enviada em Kg')),
                ('nota_fiscal', models.CharField(blank=True, max_length=255, null=True, verbose_name='Número da Nota Fiscal')),
                ('ciclo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='diamante.ciclo')),
                ('destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='related_destino_semente', to='diamante.fazenda')),
                ('origem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='related_origem_semente', to='diamante.fazenda')),
                ('safra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='diamante.safra')),
                ('variedade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='diamante.variedade')),
            ],
            options={
                'verbose_name': 'Envio de Semente',
                'verbose_name_plural': 'Envio de Sementes',
                'ordering': ['-data_envio'],
            },
        ),
    ]
