# Generated by Django 5.0 on 2024-10-03 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diamante', '0112_sentseeds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentseeds',
            name='ciclo',
            field=models.ForeignKey(blank=True, default=5, null=True, on_delete=django.db.models.deletion.PROTECT, to='diamante.ciclo'),
        ),
        migrations.AlterField(
            model_name='sentseeds',
            name='nota_fiscal',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Número da Nota Fiscal'),
        ),
        migrations.AlterField(
            model_name='sentseeds',
            name='peso_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Peso total da carga enviada em Kg'),
        ),
        migrations.AlterField(
            model_name='sentseeds',
            name='safra',
            field=models.ForeignKey(blank=True, default=3, null=True, on_delete=django.db.models.deletion.PROTECT, to='diamante.safra'),
        ),
    ]
