# Generated by Django 5.0 on 2024-10-03 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diamante', '0113_alter_sentseeds_ciclo_alter_sentseeds_nota_fiscal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentseeds',
            name='origem',
            field=models.ForeignKey(blank=True, default=17, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='related_origem_semente', to='diamante.fazenda'),
        ),
        migrations.CreateModel(
            name='SeedConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criados', models.DateTimeField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('data_apontamento', models.DateField(blank=True, help_text='dd/mm/aaaa - Data última Regulagem', null=True)),
                ('regulagem', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Regulagem das Plantadeiras em Kg/ha')),
                ('fazenda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='related_origem_semente_regulagem', to='diamante.fazenda')),
            ],
            options={
                'verbose_name': 'Regulagem da Plantadeira',
                'verbose_name_plural': 'Regulagem das Plantadeiras',
                'ordering': ['-data_apontamento'],
            },
        ),
        migrations.CreateModel(
            name='SeedStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criados', models.DateTimeField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('data_apontamento', models.DateField(blank=True, help_text='dd/mm/aaaa - Data Apontamento do Estoque', null=True)),
                ('estoque_atual', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Estoque Atual na Data em Kg')),
                ('fazenda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='related_origem_semente_estoque', to='diamante.fazenda')),
                ('variedade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='diamante.variedade')),
            ],
            options={
                'verbose_name': 'Estoque de Semente',
                'verbose_name_plural': 'Estoque de Sementes',
                'ordering': ['-data_apontamento'],
            },
        ),
    ]
