# Generated by Django 5.0 on 2024-10-03 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diamante', '0114_alter_sentseeds_origem_seedconfig_seedstock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyproducts',
            name='projeto',
            field=models.ManyToManyField(to='diamante.projeto'),
        ),
        migrations.AlterField(
            model_name='visitas',
            name='projeto',
            field=models.ManyToManyField(to='diamante.projeto'),
        ),
    ]
