# Generated by Django 5.0 on 2024-10-04 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diamante', '0115_alter_buyproducts_projeto_alter_visitas_projeto'),
    ]

    operations = [
        migrations.AddField(
            model_name='seedconfig',
            name='variedade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='diamante.variedade'),
        ),
        migrations.AlterField(
            model_name='sentseeds',
            name='peso_bag',
            field=models.DecimalField(decimal_places=2, default=700, max_digits=12, verbose_name='Peso dos Bags Enviados em Kg'),
        ),
    ]
