# Generated by Django 5.0 on 2024-10-09 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diamante', '0116_seedconfig_variedade_alter_sentseeds_peso_bag'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantio',
            name='inicializado_plantio',
            field=models.BooleanField(default=False, help_text='Informar se começou o plantio', verbose_name='Plantio Começou'),
        ),
        migrations.AddField(
            model_name='plantioextratoarea',
            name='finalizado_plantio',
            field=models.BooleanField(default=False, help_text='Informar se o plantio da parcela encerrou com', verbose_name='Plantio da parcela finalizado'),
        ),
    ]
