# Generated by Django 5.0 on 2024-10-09 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diamante', '0117_plantio_inicializado_plantio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantioextratoarea',
            name='finalizado_plantio',
            field=models.BooleanField(default=False, help_text='Informar se o plantio da parcela encerrou', verbose_name='Plantio da parcela finalizado'),
        ),
    ]
