# Generated by Django 5.0 on 2024-11-19 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diamante', '0119_plantio_farmbox_update_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aplicacao',
            name='dose',
            field=models.DecimalField(decimal_places=4, help_text='Dose aplicada de Kg ou Lt por ha.', max_digits=10, verbose_name='Dose KG/LT por ha'),
        ),
    ]
