# Generated by Django 5.0 on 2025-01-30 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diamante', '0121_programa_variedade'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='colheita',
            unique_together={('plantio', 'romaneio', 'ticket')},
        ),
        migrations.AlterField(
            model_name='programa',
            name='variedade',
            field=models.ManyToManyField(blank=True, default=None, related_name='variedade_programa', to='diamante.variedade'),
        ),
    ]
