# Generated by Django 5.0 on 2025-02-12 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diamante', '0122_alter_colheita_unique_together_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='colheita',
            index=models.Index(fields=['plantio', 'data_colheita'], name='diamante_co_plantio_36b5ee_idx'),
        ),
    ]
