# Generated by Django 5.0 on 2025-03-25 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diamante', '0123_colheita_diamante_co_plantio_36b5ee_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantio',
            name='acompanhamento_medias',
            field=models.BooleanField(default=True, help_text='Acompanha as médias do Plantio / Safra?', verbose_name='Acompanhamento das Médias'),
        ),
    ]
