# Generated by Django 5.0 on 2025-07-18 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diamante', '0124_plantio_acompanhamento_medias'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundTaskStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criados', models.DateTimeField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('task_id', models.CharField(max_length=100, unique=True)),
                ('task_name', models.CharField(max_length=100)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('result', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Background Task',
                'verbose_name_plural': 'Background Tasks',
                'ordering': ['-criados'],
            },
        ),
        migrations.AlterField(
            model_name='sentseeds',
            name='variedade',
            field=models.ForeignKey(blank=True, default=9, null=True, on_delete=django.db.models.deletion.PROTECT, to='diamante.variedade'),
        ),
    ]
