# Generated by Django 5.0 on 2025-07-19 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diamante', '0125_backgroundtaskstatus_alter_sentseeds_variedade'),
    ]

    operations = [
        migrations.CreateModel(
            name='CotacaoDolar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('valor', models.DecimalField(decimal_places=4, max_digits=10)),
            ],
            options={
                'ordering': ['-data'],
            },
        ),
        migrations.AddField(
            model_name='aplicacao',
            name='moeda',
            field=models.CharField(blank=True, choices=[('BRL', 'R$'), ('USD', 'USD')], default='BRL', max_length=3, null=True, verbose_name='Moeda'),
        ),
        migrations.AddField(
            model_name='aplicacao',
            name='preco',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=10, null=True, verbose_name='Preço unitário'),
        ),
        migrations.AddField(
            model_name='aplicacao',
            name='valor_aplicacao',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, editable=False, max_digits=14, null=True, verbose_name='Valor total aplicado (R$)'),
        ),
        migrations.AddField(
            model_name='aplicacao',
            name='valor_final',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, editable=False, max_digits=12, null=True, verbose_name='Valor final (R$)'),
        ),
    ]
