# Generated by Django 5.0 on 2025-08-01 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diamante', '0126_cotacaodolar_aplicacao_moeda_aplicacao_preco_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailAberturaST',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criados', models.DateTimeField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('email', models.EmailField(max_length=254)),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails_abertura_st', to='diamante.projeto')),
            ],
            options={
                'unique_together': {('projeto', 'email')},
            },
        ),
    ]
