# Generated by Django 5.0 on 2025-08-01 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diamante', '0127_emailaberturast'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='emailaberturast',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='emailaberturast',
            name='projetos',
            field=models.ManyToManyField(related_name='emails_abertura_st', to='diamante.projeto'),
        ),
        migrations.AlterField(
            model_name='emailaberturast',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.RemoveField(
            model_name='emailaberturast',
            name='projeto',
        ),
    ]
