# Generated by Django 5.0 on 2025-08-18 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diamante', '0128_alter_emailaberturast_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantio',
            name='data_prevista_colheita_real',
            field=models.DateField(blank=True, help_text='dd/mm/aaaa - Data Real prevista para a Colheita', null=True),
        ),
    ]
