# Generated by Django 5.0 on 2025-08-20 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diamante', '0129_plantio_data_prevista_colheita_real'),
    ]

    operations = [
        migrations.CreateModel(
            name='TiposAtividadeEmails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criados', models.DateTimeField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('tipo', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='emailaberturast',
            name='atividade',
            field=models.ManyToManyField(blank=True, related_name='atividades_emails_abertura_st', to='diamante.tiposatividadeemails'),
        ),
    ]
