# Generated by Django 5.0 on 2025-10-06 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diamante', '0130_tiposatividadeemails_emailaberturast_atividade'),
    ]

    operations = [
        migrations.AddField(
            model_name='colheita',
            name='nota_fiscal',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nota Fiscal'),
        ),
    ]
