# Generated by Django 5.0 on 2025-11-06 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diamante', '0131_colheita_nota_fiscal'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criados', models.DateTimeField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('nome', models.CharField(max_length=140, unique=True)),
                ('descricao', models.CharField(max_length=140, unique=True)),
                ('target_day', models.PositiveIntegerField(help_text='Dia ideal para a análise (ex.: 55).')),
                ('lead_days', models.PositiveIntegerField(default=0, help_text='Quantos dias antes do dia ideal a janela se abre (ex.: 5 abre a janela em 50).')),
                ('freq', models.CharField(choices=[('DAILY', 'Diário'), ('WEEKLY', 'Semanal'), ('MONTHLY', 'Mensal')], default='WEEKLY', max_length=10)),
                ('weekday', models.PositiveSmallIntegerField(default=0, help_text='0=Segunda ... 6=Domingo (use se freq for semanal).')),
                ('send_email', models.BooleanField(default=True)),
                ('send_whatsapp', models.BooleanField(default=True)),
                ('cultura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alert_rules', to='diamante.cultura')),
                ('variedade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alert_rules', to='diamante.variedade')),
            ],
            options={
                'indexes': [models.Index(fields=['ativo'], name='diamante_al_ativo_022f63_idx')],
            },
        ),
    ]
