# Generated by Django 5.0 on 2026-03-04 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diamante', '0132_alertrule'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maquina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criados', models.DateTimeField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('nome', models.CharField(max_length=120, verbose_name='Nome')),
                ('tipo', models.CharField(blank=True, default='', max_length=120, verbose_name='Tipo')),
                ('referencia', models.CharField(blank=True, default='', max_length=100, verbose_name='Referencia')),
                ('patrimonio', models.CharField(blank=True, default='', max_length=40, verbose_name='Patrimônio')),
                ('chassi', models.CharField(blank=True, default='', max_length=150, verbose_name='Chassi')),
                ('fazenda', models.ForeignKey(blank=True, help_text='Fazenda onde esta máquina normalmente fica (opcional).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='maquinas', to='diamante.fazenda')),
            ],
            options={
                'verbose_name': 'Máquina',
                'verbose_name_plural': 'Máquinas',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='operacao',
            name='maquina',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operacoes', to='diamante.maquina'),
        ),
    ]
