# Generated by Django 5.0 on 2026-03-25 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diamante', '0133_maquina_operacao_maquina'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='storage_id_farmbox',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='Storage ID FarmBox'),
        ),
    ]
