# Generated by Django 5.0 on 2026-03-26 17:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diamante', '0134_projeto_storage_id_farmbox'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmPolygon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('farm_name', models.CharField(blank=True, default='', max_length=255)),
                ('mode', models.CharField(choices=[('manual', 'Manual'), ('tracking', 'Tracking')], default='manual', max_length=20)),
                ('points', models.JSONField(blank=True, default=list)),
                ('is_closed', models.BooleanField(default=False)),
                ('area_m2', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('perimeter_m', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('observation', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='farm_polygons', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Polígono',
                'verbose_name_plural': 'Polígonos',
                'ordering': ['-created_at'],
            },
        ),
    ]
