# Generated by Django 5.0 on 2026-03-26 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diamante', '0135_farmpolygon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmpolygon',
            name='created_by',
        ),
        migrations.AddField(
            model_name='farmpolygon',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AddField(
            model_name='farmpolygon',
            name='submitted_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='farmpolygon',
            name='user_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
