# Generated by Django 5.0 on 2026-04-14 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diamante', '0136_remove_farmpolygon_created_by_farmpolygon_is_active_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stprotheusintegration',
            options={'ordering': ['-criados'], 'verbose_name': 'ST Integração', 'verbose_name_plural': 'STs Integrações'},
        ),
        migrations.AddField(
            model_name='stprotheusintegration',
            name='alerta_primeira_etapa_enviado_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Alerta 1ª etapa enviado em'),
        ),
        migrations.AddField(
            model_name='stprotheusintegration',
            name='alerta_segunda_etapa_enviado_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Alerta 2ª etapa enviado em'),
        ),
        migrations.AddField(
            model_name='stprotheusintegration',
            name='analista_disparou_em',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Analista disparou em'),
        ),
        migrations.AddField(
            model_name='stprotheusintegration',
            name='analista_payload',
            field=models.JSONField(blank=True, null=True, verbose_name='Payload analista'),
        ),
        migrations.AddField(
            model_name='stprotheusintegration',
            name='base_enviou_em',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Base enviou em'),
        ),
        migrations.AddField(
            model_name='stprotheusintegration',
            name='base_payload',
            field=models.JSONField(blank=True, null=True, verbose_name='Payload base'),
        ),
        migrations.AddField(
            model_name='stprotheusintegration',
            name='concluido_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Concluído em'),
        ),
        migrations.AddField(
            model_name='stprotheusintegration',
            name='nf_numero',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='NF número'),
        ),
        migrations.AddField(
            model_name='stprotheusintegration',
            name='prazo_primeira_etapa_horas',
            field=models.PositiveIntegerField(default=24, verbose_name='Prazo 1ª etapa (horas)'),
        ),
        migrations.AddField(
            model_name='stprotheusintegration',
            name='prazo_segunda_etapa_horas',
            field=models.PositiveIntegerField(default=24, verbose_name='Prazo 2ª etapa (horas)'),
        ),
        migrations.AddField(
            model_name='stprotheusintegration',
            name='st_gerada',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='ST gerada'),
        ),
        migrations.AddField(
            model_name='stprotheusintegration',
            name='status_fluxo',
            field=models.CharField(choices=[('aberta', 'Aberta'), ('aguardando_base', 'Aguardando base'), ('concluida', 'Concluída')], db_index=True, default='aberta', max_length=30, verbose_name='Status do fluxo'),
        ),
        migrations.AlterField(
            model_name='stprotheusintegration',
            name='st_numero',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True, verbose_name='ST Número'),
        ),
    ]
