# Generated by Django 5.0 on 2026-04-14 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diamante', '0137_alter_stprotheusintegration_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stprotheusintegration',
            name='integracao_ativa',
            field=models.BooleanField(db_index=True, default=False, help_text='Enquanto falso, a ST será tratada como concluída para não gerar atrasos falsos.', verbose_name='Integração ativa'),
        ),
    ]
