# Generated by Django 5.0 on 2026-04-16 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diamante', '0138_stprotheusintegration_integracao_ativa'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantioextratoarea',
            name='kml_area_m2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Área do KML (m²)'),
        ),
        migrations.AddField(
            model_name='plantioextratoarea',
            name='kml_content',
            field=models.TextField(blank=True, null=True, verbose_name='Conteúdo do KML'),
        ),
        migrations.AddField(
            model_name='plantioextratoarea',
            name='kml_file',
            field=models.FileField(blank=True, null=True, upload_to='plantio_extrato_area/kml/', verbose_name='Arquivo KML'),
        ),
        migrations.AddField(
            model_name='plantioextratoarea',
            name='kml_is_closed',
            field=models.BooleanField(default=True, verbose_name='Geometria fechada'),
        ),
        migrations.AddField(
            model_name='plantioextratoarea',
            name='kml_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome do KML'),
        ),
        migrations.AddField(
            model_name='plantioextratoarea',
            name='kml_perimeter_m',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Perímetro do KML (m)'),
        ),
        migrations.AddField(
            model_name='plantioextratoarea',
            name='kml_points',
            field=models.JSONField(blank=True, default=list, help_text="Lista normalizada de pontos no formato [{'lat': ..., 'lng': ...}]", null=True, verbose_name='Pontos do KML'),
        ),
    ]
