# Generated by Django 5.0 on 2026-05-15 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diamante', '0139_plantioextratoarea_kml_area_m2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backgroundtaskstatus',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
