# Generated by Django 5.0 on 2026-05-26 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diamante', '0140_alter_backgroundtaskstatus_started_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmboxPlantioSyncState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criados', models.DateTimeField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('last_sync_at', models.DateTimeField(blank=True, null=True, verbose_name='Última sincronização')),
                ('last_updated_since_ms', models.BigIntegerField(blank=True, null=True, verbose_name='Último updated_since enviado')),
                ('last_total_received', models.PositiveIntegerField(default=0, verbose_name='Último total recebido')),
                ('last_result', models.JSONField(blank=True, null=True, verbose_name='Último resultado')),
                ('safra', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='farmbox_sync_state', to='diamante.safra')),
            ],
            options={
                'verbose_name': 'Sync Plantio Farmbox',
                'verbose_name_plural': 'Sync Plantios Farmbox',
            },
        ),
    ]
