# Generated by Django 5.0 on 2026-02-25 19:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opscheckin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InboundMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_phone', models.CharField(db_index=True, max_length=20)),
                ('wa_message_id', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('text', models.TextField(blank=True, default='')),
                ('msg_type', models.CharField(blank=True, default='text', max_length=32)),
                ('received_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('processed', models.BooleanField(db_index=True, default=False)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('raw_payload', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='dailycheckin',
            index=models.Index(fields=['manager', 'date'], name='opscheckin__manager_1242c7_idx'),
        ),
        migrations.AddIndex(
            model_name='outboundquestion',
            index=models.Index(fields=['checkin', 'status', 'answered_at'], name='opscheckin__checkin_9656a4_idx'),
        ),
        migrations.AddIndex(
            model_name='outboundquestion',
            index=models.Index(fields=['checkin', 'step'], name='opscheckin__checkin_0466f7_idx'),
        ),
        migrations.AddField(
            model_name='inboundmessage',
            name='checkin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inbound_messages', to='opscheckin.dailycheckin'),
        ),
        migrations.AddField(
            model_name='inboundmessage',
            name='linked_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inbound_messages', to='opscheckin.outboundquestion'),
        ),
        migrations.AddField(
            model_name='inboundmessage',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inbound_messages', to='opscheckin.manager'),
        ),
        migrations.AddIndex(
            model_name='inboundmessage',
            index=models.Index(fields=['from_phone', 'received_at'], name='opscheckin__from_ph_cb923a_idx'),
        ),
        migrations.AddIndex(
            model_name='inboundmessage',
            index=models.Index(fields=['manager', 'received_at'], name='opscheckin__manager_4d0e2f_idx'),
        ),
        migrations.AddIndex(
            model_name='inboundmessage',
            index=models.Index(fields=['processed', 'received_at'], name='opscheckin__process_e30247_idx'),
        ),
    ]
