# Generated by Django 5.0 on 2026-02-26 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opscheckin', '0002_inboundmessage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='outboundquestion',
            name='prompt_text',
            field=models.TextField(blank=True, default=''),
        ),
    ]
