# Generated by Django 5.0 on 2026-02-26 20:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opscheckin', '0003_outboundquestion_prompt_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutboundMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_phone', models.CharField(db_index=True, max_length=20)),
                ('provider_message_id', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('kind', models.CharField(choices=[('agenda', 'Agenda'), ('reminder', 'Reminder'), ('manual', 'Manual'), ('other', 'Other')], db_index=True, default='text', max_length=24)),
                ('text', models.TextField(blank=True, default='')),
                ('sent_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('raw_response', models.JSONField(blank=True, null=True)),
                ('checkin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outbound_messages', to='opscheckin.dailycheckin')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outbound_messages', to='opscheckin.manager')),
                ('related_question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outbound_messages', to='opscheckin.outboundquestion')),
            ],
            options={
                'indexes': [models.Index(fields=['to_phone', 'sent_at'], name='opscheckin__to_phon_a73963_idx'), models.Index(fields=['manager', 'sent_at'], name='opscheckin__manager_10acae_idx'), models.Index(fields=['checkin', 'sent_at'], name='opscheckin__checkin_ef7dc0_idx'), models.Index(fields=['kind', 'sent_at'], name='opscheckin__kind_977681_idx')],
            },
        ),
    ]
