# Generated by Django 5.0 on 2026-03-04 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opscheckin', '0004_outboundmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='outboundmessage',
            name='wa_delivered_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='outboundmessage',
            name='wa_last_status_payload',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='outboundmessage',
            name='wa_read_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='outboundmessage',
            name='wa_sent_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='outboundmessage',
            name='wa_status',
            field=models.CharField(blank=True, choices=[('', 'Unknown'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('read', 'Read'), ('failed', 'Failed')], db_index=True, default='', max_length=16),
        ),
    ]
