# Generated by Django 5.0 on 2026-03-04 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opscheckin', '0005_outboundmessage_wa_delivered_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgendaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idx', models.IntegerField()),
                ('text', models.CharField(max_length=280)),
                ('status', models.CharField(choices=[('open', 'Open'), ('done', 'Done'), ('skip', 'Skip')], default='open', max_length=16)),
                ('done_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('checkin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agenda_items', to='opscheckin.dailycheckin')),
            ],
        ),
    ]
