# Generated by Django 5.0 on 2026-03-06 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opscheckin', '0006_agendaitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=60, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo de notificação',
                'verbose_name_plural': 'Tipos de notificação',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='ManagerNotificationSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_subscriptions', to='opscheckin.manager')),
                ('notification_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='opscheckin.notificationtype')),
            ],
            options={
                'verbose_name': 'Assinatura de notificação',
                'verbose_name_plural': 'Assinaturas de notificações',
            },
        ),
        migrations.AddField(
            model_name='manager',
            name='notification_types',
            field=models.ManyToManyField(blank=True, related_name='managers', through='opscheckin.ManagerNotificationSubscription', to='opscheckin.notificationtype'),
        ),
        migrations.AddIndex(
            model_name='managernotificationsubscription',
            index=models.Index(fields=['manager', 'is_active'], name='opscheckin__manager_1ced44_idx'),
        ),
        migrations.AddIndex(
            model_name='managernotificationsubscription',
            index=models.Index(fields=['notification_type', 'is_active'], name='opscheckin__notific_2e9fe4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='managernotificationsubscription',
            unique_together={('manager', 'notification_type')},
        ),
    ]
