# Generated by Django 5.0 on 2026-03-11 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opscheckin', '0007_notificationtype_managernotificationsubscription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='is_active_resume_agenda',
            field=models.BooleanField(default=False, help_text='Recebe o resumo consolidado da agenda (diretoria)'),
        ),
        migrations.AlterField(
            model_name='manager',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Participa do fluxo de agenda diária'),
        ),
    ]
