# Generated by Django 5.0 on 2026-03-12 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opscheckin', '0008_manager_is_active_resume_agenda_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='phone_e164',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
