# Generated by Django 5.0 on 2026-03-12 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opscheckin', '0009_alter_manager_phone_e164'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outboundmessage',
            name='kind',
            field=models.CharField(choices=[('agenda', 'Agenda'), ('reminder', 'Reminder'), ('manual', 'Manual'), ('other', 'Other'), ('agenda_summary_director', 'Resumo diretoria'), ('agenda_summary_director_overview', 'Resumo diretoria geral'), ('agenda_summary_director_actions', 'Ações resumo diretoria')], db_index=True, default='text', max_length=150),
        ),
    ]
