# Generated by Django 5.0 on 2026-03-13 17:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opscheckin', '0010_alter_outboundmessage_kind'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyManagerEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('farm_daily_agenda', 'Agenda diária da fazenda')], max_length=60, unique=True)),
                ('name', models.CharField(default='Agenda diária da fazenda', max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('default_time', models.TimeField()),
                ('override_date', models.DateField(blank=True, null=True)),
                ('override_time', models.TimeField(blank=True, null=True)),
                ('meet_link', models.URLField(blank=True, default='')),
                ('template_name', models.CharField(blank=True, default='daily_meeting_reminder', max_length=120)),
                ('template_language', models.CharField(default='pt_BR', max_length=20)),
                ('template_enabled', models.BooleanField(default=False)),
                ('reminder_offset_minutes', models.PositiveSmallIntegerField(default=60)),
                ('allowed_window_minutes', models.PositiveSmallIntegerField(default=90)),
                ('last_reset_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DailyManagerEventDispatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', models.DateField(db_index=True)),
                ('scheduled_event_time', models.TimeField()),
                ('target_send_time', models.TimeField()),
                ('sent_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('provider_message_id', models.CharField(blank=True, default='', max_length=128)),
                ('status', models.CharField(default='sent', max_length=20)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispatches', to='opscheckin.dailymanagerevent')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_dispatches', to='opscheckin.manager')),
            ],
            options={
                'unique_together': {('event', 'manager', 'event_date', 'target_send_time')},
            },
        ),
    ]
