# Generated by Django 5.0 on 2026-03-13 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opscheckin', '0011_dailymanagerevent_dailymanagereventdispatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='is_active_for_meetings',
            field=models.BooleanField(default=False, help_text='Recebe lembretes de reuniões diárias'),
        ),
        migrations.AlterField(
            model_name='outboundmessage',
            name='kind',
            field=models.CharField(choices=[('agenda', 'Agenda'), ('reminder', 'Reminder'), ('manual', 'Manual'), ('other', 'Other'), ('agenda_summary_director', 'Resumo diretoria'), ('agenda_summary_director_overview', 'Resumo diretoria geral'), ('agenda_summary_director_actions', 'Ações resumo diretoria'), ('daily_meeting_reminder', 'Lembrete reunião diária')], db_index=True, default='text', max_length=150),
        ),
    ]
