# Generated by Django 5.0 on 2026-03-16 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opscheckin', '0012_manager_is_active_for_meetings_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dailymanagereventdispatch',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='dailymanagereventdispatch',
            constraint=models.UniqueConstraint(fields=('event', 'manager', 'event_date', 'scheduled_event_time', 'target_send_time'), name='uniq_daily_manager_event_dispatch_slot'),
        ),
    ]
