# Generated by Django 5.0 on 2026-04-14 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diamante', '0136_remove_farmpolygon_created_by_farmpolygon_is_active_and_more'),
        ('opscheckin', '0013_alter_dailymanagereventdispatch_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='id_responsavel_farmbox',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='ID FarmBox'),
        ),
        migrations.AddField(
            model_name='manager',
            name='projeto',
            field=models.ManyToManyField(blank=True, default=None, related_name='projeto_manager', to='diamante.projeto'),
        ),
        migrations.AlterField(
            model_name='outboundmessage',
            name='kind',
            field=models.CharField(choices=[('agenda', 'Agenda'), ('reminder', 'Reminder'), ('manual', 'Manual'), ('other', 'Other'), ('agenda_summary_director', 'Resumo diretoria'), ('agenda_summary_director_overview', 'Resumo diretoria geral'), ('agenda_summary_director_actions', 'Ações resumo diretoria'), ('daily_meeting_reminder', 'Lembrete reunião diária'), ('daily_meeting_reminder_changed', 'Lembrete reunião diária alterada')], db_index=True, default='text', max_length=150),
        ),
    ]
