# Generated by Django 5.0 on 2026-04-17 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opscheckin', '0014_manager_id_responsavel_farmbox_manager_projeto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailymanagerevent',
            name='skip_meeting_on',
            field=models.DateField(blank=True, db_index=True, help_text='Se preenchido com a data de hoje, o sistema não envia os lembretes apenas nesse dia.', null=True, verbose_name='Pular reunião na data'),
        ),
    ]
