# Generated by Django 5.0 on 2026-04-20 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opscheckin', '0015_dailymanagerevent_skip_meeting_on'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=80, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Filial',
                'verbose_name_plural': 'Filiais',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=80, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Divisão',
                'verbose_name_plural': 'Divisões',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='dailymanagerevent',
            name='applies_to_all',
            field=models.BooleanField(default=True, help_text='Quando ativo, ignora filtros de divisão e filial.'),
        ),
        migrations.AddField(
            model_name='dailymanagerevent',
            name='target_branches',
            field=models.ManyToManyField(blank=True, related_name='daily_manager_events', to='opscheckin.branch', verbose_name='Filiais alvo'),
        ),
        migrations.AddField(
            model_name='manager',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managers', to='opscheckin.branch', verbose_name='Filial'),
        ),
        migrations.AddField(
            model_name='dailymanagerevent',
            name='target_divisions',
            field=models.ManyToManyField(blank=True, related_name='daily_manager_events', to='opscheckin.division', verbose_name='Divisões alvo'),
        ),
        migrations.AddField(
            model_name='manager',
            name='division',
            field=models.ManyToManyField(blank=True, related_name='managers', to='opscheckin.division', verbose_name='Divisões'),
        ),
    ]
