# Generated by Django 5.0 on 2026-04-23 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opscheckin', '0016_branch_division_dailymanagerevent_applies_to_all_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outboundmessage',
            name='kind',
            field=models.CharField(choices=[('agenda', 'Agenda'), ('reminder', 'Reminder'), ('manual', 'Manual'), ('other', 'Other'), ('agenda_summary_director', 'Resumo diretoria'), ('agenda_summary_director_overview', 'Resumo diretoria geral'), ('agenda_summary_director_actions', 'Ações resumo diretoria'), ('daily_meeting_reminder', 'Lembrete reunião diária'), ('daily_meeting_reminder_changed', 'Lembrete reunião diária alterada'), ('personal_reminder', 'Aviso pessoal')], db_index=True, default='text', max_length=150),
        ),
        migrations.CreateModel(
            name='ManagerPersonalReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, db_index=True, default='', max_length=80)),
                ('title', models.CharField(max_length=120, verbose_name='Título')),
                ('description', models.CharField(blank=True, default='', max_length=255, verbose_name='Descrição interna')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('schedule_type', models.CharField(choices=[('daily', 'Diário'), ('weekly', 'Semanal'), ('monthly', 'Mensal')], db_index=True, default='daily', max_length=16, verbose_name='Periodicidade')),
                ('time_of_day', models.TimeField(verbose_name='Horário do envio')),
                ('weekday', models.PositiveSmallIntegerField(blank=True, help_text='0=segunda ... 6=domingo. Usado apenas no semanal.', null=True, verbose_name='Dia da semana')),
                ('day_of_month', models.PositiveSmallIntegerField(blank=True, help_text='Usado apenas no mensal.', null=True, verbose_name='Dia do mês')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Início')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Fim')),
                ('delivery_mode', models.CharField(choices=[('text', 'Somente texto'), ('template', 'Template WhatsApp')], default='text', max_length=16, verbose_name='Modo de envio')),
                ('response_mode', models.CharField(choices=[('none', 'Sem resposta'), ('text', 'Resposta por texto'), ('button', 'Botão de confirmação')], default='none', help_text='Define se o aviso exige botão, texto ou não exige retorno.', max_length=16, verbose_name='Tipo de resposta')),
                ('message_text', models.TextField(blank=True, default='', verbose_name='Mensagem')),
                ('template_name', models.CharField(blank=True, default='', max_length=120, verbose_name='Nome do template')),
                ('template_language', models.CharField(default='pt_BR', max_length=20, verbose_name='Idioma do template')),
                ('allowed_window_minutes', models.PositiveSmallIntegerField(default=30, verbose_name='Janela de envio (min)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_reminders', to='opscheckin.manager', verbose_name='Manager')),
            ],
            options={
                'verbose_name': 'Aviso pessoal do manager',
                'verbose_name_plural': 'Avisos pessoais dos managers',
                'ordering': ['manager__name', 'time_of_day', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ManagerPersonalReminderDispatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_date', models.DateField(db_index=True, verbose_name='Data de referência')),
                ('scheduled_for', models.DateTimeField(db_index=True, verbose_name='Agendado para')),
                ('sent_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('provider_message_id', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('sent', 'Enviado'), ('answered', 'Respondido'), ('missed', 'Expirado'), ('failed', 'Falhou')], db_index=True, default='pending', max_length=16)),
                ('answered_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Respondido em')),
                ('answer_text', models.TextField(blank=True, default='', verbose_name='Resposta')),
                ('answer_source', models.CharField(choices=[('none', 'Sem resposta'), ('text', 'Texto'), ('button', 'Botão'), ('manual', 'Manual')], default='none', max_length=16, verbose_name='Origem da resposta')),
                ('raw_response_payload', models.JSONField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inbound_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personal_reminder_dispatches', to='opscheckin.inboundmessage')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_reminder_dispatches', to='opscheckin.manager', verbose_name='Manager')),
                ('outbound_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personal_reminder_dispatches', to='opscheckin.outboundmessage')),
                ('reminder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispatches', to='opscheckin.managerpersonalreminder', verbose_name='Aviso')),
            ],
            options={
                'verbose_name': 'Disparo de aviso pessoal',
                'verbose_name_plural': 'Disparos de avisos pessoais',
                'ordering': ['-scheduled_for', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='managerpersonalreminder',
            index=models.Index(fields=['manager', 'is_active'], name='opscheckin__manager_1b66b6_idx'),
        ),
        migrations.AddIndex(
            model_name='managerpersonalreminder',
            index=models.Index(fields=['schedule_type', 'is_active'], name='opscheckin__schedul_debf81_idx'),
        ),
        migrations.AddIndex(
            model_name='managerpersonalreminder',
            index=models.Index(fields=['time_of_day', 'is_active'], name='opscheckin__time_of_bacb1d_idx'),
        ),
        migrations.AddIndex(
            model_name='managerpersonalreminderdispatch',
            index=models.Index(fields=['manager', 'status', 'scheduled_for'], name='opscheckin__manager_3413c4_idx'),
        ),
        migrations.AddIndex(
            model_name='managerpersonalreminderdispatch',
            index=models.Index(fields=['reminder', 'reference_date'], name='opscheckin__reminde_69c410_idx'),
        ),
        migrations.AddIndex(
            model_name='managerpersonalreminderdispatch',
            index=models.Index(fields=['provider_message_id'], name='opscheckin__provide_616539_idx'),
        ),
        migrations.AddConstraint(
            model_name='managerpersonalreminderdispatch',
            constraint=models.UniqueConstraint(fields=('reminder', 'manager', 'reference_date'), name='uniq_manager_personal_reminder_dispatch_day'),
        ),
    ]
