# Generated by Django 5.0 on 2026-04-23 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opscheckin', '0017_alter_outboundmessage_kind_managerpersonalreminder_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managerpersonalreminder',
            name='delivery_mode',
            field=models.CharField(choices=[('text', 'Somente texto'), ('template', 'Template WhatsApp')], default='template', max_length=16, verbose_name='Modo de envio'),
        ),
    ]
