# Generated by Django 5.0 on 2026-04-30 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opscheckin', '0018_alter_managerpersonalreminder_delivery_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='coordinator',
            field=models.ForeignKey(blank=True, help_text='Coordenador responsável por receber confirmações e resumos dos avisos pessoais deste manager.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coordinated_managers', to='opscheckin.manager', verbose_name='Coordenador'),
        ),
        migrations.AddField(
            model_name='manager',
            name='is_personal_reminder_coordinator',
            field=models.BooleanField(default=False, help_text='Recebe confirmações e resumo diário dos avisos pessoais dos managers relacionados.', verbose_name='Coordenador de avisos pessoais'),
        ),
        migrations.AlterField(
            model_name='outboundmessage',
            name='kind',
            field=models.CharField(choices=[('agenda', 'Agenda'), ('reminder', 'Reminder'), ('manual', 'Manual'), ('other', 'Other'), ('agenda_summary_director', 'Resumo diretoria'), ('agenda_summary_director_overview', 'Resumo diretoria geral'), ('agenda_summary_director_actions', 'Ações resumo diretoria'), ('daily_meeting_reminder', 'Lembrete reunião diária'), ('daily_meeting_reminder_changed', 'Lembrete reunião diária alterada'), ('personal_reminder', 'Aviso pessoal'), ('personal_reminder_coordinator_notice', 'Aviso ao coordenador'), ('personal_reminder_coordinator_daily_action', 'Botão resumo diário avisos'), ('personal_reminder_coordinator_daily_summary', 'Resumo diário avisos'), ('manual_template', 'Manual via template')], db_index=True, default='text', max_length=150),
        ),
    ]
