# Generated by Django 5.0 on 2026-04-30 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opscheckin', '0019_manager_coordinator_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manager',
            name='coordinator',
        ),
        migrations.AddField(
            model_name='manager',
            name='personal_reminder_managers',
            field=models.ManyToManyField(blank=True, help_text='Managers/funcionários cujos avisos pessoais serão acompanhados por este coordenador.', related_name='personal_reminder_coordinators', to='opscheckin.manager', verbose_name='Managers sob coordenação'),
        ),
    ]
