# Generated by Django 5.0 on 2026-04-30 12:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opscheckin', '0020_remove_manager_coordinator_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OpsBoardAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coordinator', models.ForeignKey(help_text='Coordenador cujo grupo este usuário poderá visualizar no board.', limit_choices_to={'is_personal_reminder_coordinator': True}, on_delete=django.db.models.deletion.CASCADE, related_name='board_accesses', to='opscheckin.manager', verbose_name='Coordenador')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ops_board_access', to=settings.AUTH_USER_MODEL, verbose_name='Usuário Django')),
            ],
            options={
                'verbose_name': 'Acesso ao Board OpsCheckin',
                'verbose_name_plural': 'Acessos ao Board OpsCheckin',
            },
        ),
    ]
