# Generated by Django 5.0 on 2026-05-14 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opscheckin', '0022_alter_outboundmessage_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outboundmessage',
            name='kind',
            field=models.CharField(choices=[('agenda', 'Agenda'), ('reminder', 'Reminder'), ('manual', 'Manual'), ('other', 'Other'), ('agenda_summary_director', 'Resumo diretoria'), ('agenda_summary_director_overview', 'Resumo diretoria geral'), ('agenda_summary_director_actions', 'Ações resumo diretoria'), ('daily_meeting_reminder', 'Lembrete reunião diária'), ('daily_meeting_reminder_changed', 'Lembrete reunião diária alterada'), ('personal_reminder', 'Aviso pessoal'), ('personal_reminder_coordinator_notice', 'Aviso ao coordenador'), ('personal_reminder_coordinator_daily_action', 'Botão resumo diário avisos'), ('personal_reminder_coordinator_daily_summary', 'Resumo diário avisos'), ('manual_template', 'Manual via template'), ('machine_update_confirmation', 'Confirmação atualização de máquina'), ('machine_revision_confirmation', 'Confirmação revisão de máquina'), ('machine_update_applied', 'Atualização de máquina aplicada'), ('machine_update_field_manager_notice', 'Aviso atualização maquinário'), ('machine_revision_alert', 'Alerta revisão de máquina'), ('machine_hourmeter_stale_update_request', 'Solicitação horímetro desatualizado'), ('machine_hourmeter_stale_field_manager_notice', 'Aviso horímetro desatualizado ao gerente de campo')], db_index=True, default='text', max_length=150),
        ),
    ]
