# Generated by Django 4.1.7 on 2023-03-30 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_alter_customusuario_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customusuario',
            name='image',
        ),
    ]
