# Generated by Django 5.0 on 2026-02-05 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_alter_customusuario_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusuario',
            name='origin_app',
            field=models.CharField(choices=[('diamante', 'Diamante'), ('kmltools', 'KML Tools'), ('unknown', 'Unknown'), ('outro_app', 'Outro App')], db_index=True, default='unknown', max_length=32),
        ),
    ]
