# Generated by Django 5.0 on 2026-01-07 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kmltools', '0002_weeklyusage'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingprofile',
            name='current_period_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='billingprofile',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='billingprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
