# Generated by Django 5.0 on 2026-01-08 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kmltools', '0003_billingprofile_current_period_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingprofile',
            name='cancel_at_period_end',
            field=models.BooleanField(default=False),
        ),
    ]
