# Generated by Django 5.0 on 2026-01-09 14:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kmltools', '0004_billingprofile_cancel_at_period_end'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KMLMergeJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_id', models.CharField(db_index=True, max_length=64)),
                ('plan', models.CharField(db_index=True, default='free', max_length=32)),
                ('status', models.CharField(choices=[('success', 'Success'), ('error', 'Error')], db_index=True, default='success', max_length=16)),
                ('tol_m', models.FloatField(default=20.0)),
                ('corridor_width_m', models.FloatField(default=1.0)),
                ('total_files', models.IntegerField(default=0)),
                ('total_polygons', models.IntegerField(default=0)),
                ('output_polygons', models.IntegerField(blank=True, null=True)),
                ('merged_polygons', models.IntegerField(blank=True, null=True)),
                ('input_area_m2', models.FloatField(blank=True, null=True)),
                ('input_area_ha', models.FloatField(blank=True, null=True)),
                ('output_area_m2', models.FloatField(blank=True, null=True)),
                ('output_area_ha', models.FloatField(blank=True, null=True)),
                ('storage_path', models.CharField(blank=True, default='', max_length=512)),
                ('metrics', models.JSONField(blank=True, default=dict)),
                ('input_filenames', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kml_merge_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', '-created_at'], name='kmltools_km_user_id_b8a0ad_idx'), models.Index(fields=['request_id'], name='kmltools_km_request_762827_idx')],
            },
        ),
    ]
