# Generated by Django 5.0 on 2026-01-23 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kmltools', '0005_kmlmergejob'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingprofile',
            name='credits_used_total',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='billingprofile',
            name='free_month_key',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='billingprofile',
            name='free_monthly_credits',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='billingprofile',
            name='prepaid_credits',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='billingprofile',
            name='plan',
            field=models.CharField(choices=[('free', 'Free'), ('prepaid', 'Prepaid'), ('pro_monthly', 'Pro Monthly'), ('pro_yearly', 'Pro Yearly'), ('pro', 'Pro')], default='free', max_length=20),
        ),
    ]
