# Generated by Django 5.0 on 2026-01-26 13:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kmltools', '0006_billingprofile_credits_used_total_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MergeFeedback',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('source', models.CharField(blank=True, default='ui', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('merge_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='kmltools.kmlmergejob')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kml_merge_feedbacks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', '-created_at'], name='kmltools_me_user_id_4228a0_idx'), models.Index(fields=['merge_job', '-created_at'], name='kmltools_me_merge_j_cfeb90_idx')],
            },
        ),
    ]
