# Generated by Django 5.0 on 2026-01-26 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kmltools', '0007_mergefeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='kmlmergejob',
            name='download_email_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kmlmergejob',
            name='input_storage_paths',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kmlmergejob',
            name='meta_storage_path',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
