# Generated by Django 5.0 on 2026-02-15 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kmltools', '0008_kmlmergejob_download_email_sent_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingprofile',
            name='onboarding_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='billingprofile',
            name='onboarding_skipped_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='billingprofile',
            name='usage_frequency',
            field=models.CharField(blank=True, db_index=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='billingprofile',
            name='use_case',
            field=models.CharField(blank=True, db_index=True, default='', max_length=32),
        ),
    ]
