# Generated by Django 5.0 on 2026-02-22 01:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kmltools', '0010_kmlmergejob_anon_id_alter_kmlmergejob_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='billingprofile',
            name='free_unlock_used',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='UnlockFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anon_id', models.CharField(blank=True, max_length=120, null=True)),
                ('use_case', models.CharField(max_length=100)),
                ('frequency', models.CharField(max_length=50)),
                ('willingness', models.CharField(max_length=50)),
                ('price_expectation', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
