# Generated by Django 5.0 on 2026-02-22 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kmltools', '0011_billingprofile_free_unlock_used_unlockfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='unlockfeedback',
            name='other_use_case_text',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
