# Generated by Django 5.0 on 2026-02-24 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kmltools', '0012_unlockfeedback_other_use_case_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingprofile',
            name='country',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='billingprofile',
            name='country_name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='billingprofile',
            name='country_set_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='billingprofile',
            name='country_source',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
