# Generated by Django 5.0 on 2026-02-25 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kmltools', '0013_billingprofile_country_billingprofile_country_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kmlmergejob',
            name='visitor_country',
            field=models.CharField(blank=True, db_index=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='kmlmergejob',
            name='visitor_country_name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='kmlmergejob',
            name='visitor_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
