# Generated by Django 5.0 on 2026-03-13 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kmltools', '0014_kmlmergejob_visitor_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unlockfeedback',
            name='anon_id',
            field=models.CharField(blank=True, db_index=True, max_length=120, null=True),
        ),
    ]
