# Generated by Django 5.0 on 2026-03-13 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kmltools', '0015_alter_unlockfeedback_anon_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='unlockfeedback',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, db_index=True, null=True),
        ),
    ]
