# Generated by Django 5.0 on 2026-04-08 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kmltools', '0016_unlockfeedback_ip_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingprofile',
            name='remove_from_mail_list',
            field=models.BooleanField(default=False),
        ),
    ]
