# Generated by Django 5.0 on 2026-04-15 16:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kmltools', '0017_billingprofile_remove_from_mail_list'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='kmlmergejob',
            name='status',
            field=models.CharField(choices=[('success', 'Success'), ('error', 'Error'), ('queued', 'Queued'), ('processing', 'Processing')], db_index=True, default='success', max_length=16),
        ),
        migrations.AlterField(
            model_name='kmlmergejob',
            name='visitor_ip',
            field=models.GenericIPAddressField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name='kmlmergejob',
            index=models.Index(fields=['-created_at', 'id'], name='kmltools_km_created_2944e7_idx'),
        ),
    ]
