# Generated by Django 5.0 on 2026-04-28 10:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kmltools', '0018_alter_kmlmergejob_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailMagicLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('token_hash', models.CharField(db_index=True, max_length=128, unique=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('firebase_uid', models.CharField(blank=True, default='', max_length=128)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='kmlmergejob',
            name='kmltools_km_created_2944e7_idx',
        ),
        migrations.AddIndex(
            model_name='kmlmergejob',
            index=models.Index(fields=['-created_at', '-id'], name='kmltools_km_created_ec7844_idx'),
        ),
        migrations.AddIndex(
            model_name='kmlmergejob',
            index=models.Index(fields=['anon_id'], name='kmltools_km_anon_id_d77176_idx'),
        ),
        migrations.AddIndex(
            model_name='kmlmergejob',
            index=models.Index(fields=['visitor_ip'], name='kmltools_km_visitor_64ae61_idx'),
        ),
        migrations.AddIndex(
            model_name='kmlmergejob',
            index=models.Index(fields=['plan'], name='kmltools_km_plan_ee719b_idx'),
        ),
        migrations.AddIndex(
            model_name='kmlmergejob',
            index=models.Index(fields=['visitor_country'], name='kmltools_km_visitor_e630c2_idx'),
        ),
        migrations.AddIndex(
            model_name='emailmagiclink',
            index=models.Index(fields=['email', '-created_at'], name='kmltools_em_email_8ec914_idx'),
        ),
        migrations.AddIndex(
            model_name='emailmagiclink',
            index=models.Index(fields=['expires_at'], name='kmltools_em_expires_2d0c32_idx'),
        ),
    ]
