# Generated by Django 5.0 on 2026-04-30 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kmltools', '0019_emailmagiclink_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kmlmergejob',
            name='download_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='kmlmergejob',
            name='download_credit_consumed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='kmlmergejob',
            name='download_unlock_source',
            field=models.CharField(blank=True, db_index=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='kmlmergejob',
            name='download_unlocked',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='kmlmergejob',
            name='download_unlocked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kmlmergejob',
            name='first_downloaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kmlmergejob',
            name='last_downloaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
