# Generated by Django 5.0 on 2026-05-11 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kmltools', '0020_kmlmergejob_download_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kmlmergejob',
            name='recovery_email_last_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='kmlmergejob',
            name='recovery_email_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kmlmergejob',
            name='recovery_email_sent_to',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
    ]
